# -*- coding: utf-8 -*-
"""Lote "p5_ajuda": traduções pt -> ja."""
TRAD = {
    "A <b>primeira</b> abertura depois de instalar ou atualizar prepara um cache (pasta <b>.roa_cache</b>, ao lado do programa ou na pasta ROA dos dados locais do usuário) e por isso demora mais; as seguintes abrem em poucos segundos. A tela de abertura com o logo diz em palavras o que está sendo carregado. Se a demora continuar, confira se o antivírus não examina a pasta do programa a cada abertura.": "インストールや更新後の<b>最初</b>の起動ではキャッシュ（プログラムの隣、またはユーザーのローカルデータの ROA フォルダー内の <b>.roa_cache</b> フォルダー）を準備するため時間がかかります。次回からは数秒で開きます。ロゴ付きの起動画面には、読み込み中の内容が言葉で表示されます。遅いままなら、ウイルス対策ソフトが起動のたびにプログラムのフォルダーを検査していないか確認してください。",
    "A animação <b>simula</b> o que foi gravado a partir dos sinais: não é vídeo da pessoa, e não é laudo nem diagnóstico.": "アニメーションは信号から記録内容を<b>再現（シミュレーション）</b>したものです。本人の映像ではなく、報告書でも診断でもありません。",
    "A figura não se mexe": "人形が動かない",
    "Abra o Replay da gravação de músculos no nível <b>Completo</b>.": "<b>完全</b>レベルで筋肉の記録のリプレイを開きます。",
    "Arraste a linha do tempo para ir a um instante. Na lista ao lado, clique em um trecho, uma batida ou um evento para o tocador pular até lá.": "タイムラインをドラッグして任意の時点へ移動します。横のリストで区間・拍・イベントをクリックすると、プレーヤーがそこへ飛びます。",
    "Arraste o ponto para ajustar; duplo clique renomeia; <b>Delete</b> remove o selecionado.": "点をドラッグして調整します。ダブルクリックで名前変更、<b>Delete</b> で選択した電極を削除します。",
    "Arraste um bloco para movê-lo e puxe a borda para esticar. <b>Dividir aqui</b> corta um trecho em dois; <b>Adicionar faixa</b> cria outra faixa para movimentos ao mesmo tempo (até quatro).": "ブロックをドラッグして移動し、端を引いて伸ばします。<b>ここで分割</b>は区間を二つに切り、<b>トラックを追加</b>は同時に起こる動作のための別トラックを作ります（最大 4 本）。",
    "As batidas e os eventos dos olhos são os mesmos do relatório PDF; corrigi-los (nível Completo) não altera a gravação, só o arquivo do Replay ao lado dela.": "拍と目のイベントは PDF 報告書と同じものです。修正（完全レベル）しても記録は変わらず、記録の隣にあるリプレイのファイルだけが変わります。",
    "As listas de canais mostram só os canais <b>em uso</b> no exame escolhido. Ao rever uma gravação, as listas seguem os canais daquela gravação, não os do aparelho ligado agora.": "チャンネル一覧には、選んだ検査で<b>使用中</b>のチャンネルだけが表示されます。記録を見直すときは、一覧は今つながっている機器ではなく、その記録のチャンネルに従います。",
    "As listas de canais mostram só os canais <b>em uso</b>: ligados e do tipo do exame (um canal marcado como coração não aparece na lista de músculos). Para mudar o tipo ou religar um canal, use <b>Filtros e Canais</b> no nível Completo. Ao rever uma gravação, as listas seguem os canais daquela gravação.": "チャンネル一覧には<b>使用中</b>のチャンネルだけが表示されます。オンで、検査の種類に合うもの（心臓と指定したチャンネルは筋肉の一覧に出ません）。種類の変更やチャンネルの再オンは、完全レベルの<b>フィルターとチャンネル</b>で行います。記録を見直すときは、一覧はその記録のチャンネルに従います。",
    "Clique em <b>Adicionar eletrodo</b> e depois no corpo: o ponto cola no lugar recomendado do músculo mais próximo (ventre do músculo, referência SENIAM).": "<b>電極を追加</b>をクリックしてから体をクリックします。点は最も近い筋肉の推奨位置（筋腹、SENIAM 基準）に吸着します。",
    "Clique em <b>▶ Replay</b>. A janela abre com o tocador: <b>▶ Tocar</b>, <b>⏸ Pausar</b>, <b>⏮ Início</b>, a linha do tempo e o relógio.": "<b>▶ リプレイ</b>をクリックします。プレーヤー付きのウィンドウが開きます：<b>▶ 再生</b>、<b>⏸ 一時停止</b>、<b>⏮ 先頭</b>、タイムライン、時計。",
    "Colocar os eletrodos no desenho do corpo": "体の図に電極を配置する",
    "Ctrl+Z desfaz. Clique em <b>Salvar</b>: o arquivo movimentos.json fica ao lado da gravação e é lido da próxima vez.": "Ctrl+Z で元に戻します。<b>保存</b>をクリックすると、movimentos.json ファイルが記録の隣に保存され、次回読み込まれます。",
    "De frente, o lado <b>direito</b> da pessoa fica à <b>esquerda</b> do desenho, como numa foto; confira o D/E no nome do músculo.": "正面から見ると、本人の<b>右</b>側は図の<b>左</b>側にあります（写真と同じ）。筋肉名の右/左を確認してください。",
    "Durante o exame, a mancha de calor no ponto do eletrodo mostra a intensidade medida ali; o anel em volta do número mostra a qualidade do sinal.": "検査中、電極の点の熱い斑点はそこで測った強さを示し、番号の周りのリングは信号の質を示します。",
    "Em <b>Rever uma gravação</b>, escolha uma gravação de músculos, coração ou olhos e clique em <b>▶ Replay</b>. Uma figura refaz o movimento marcado, um coração bate no ritmo gravado ou dois olhos piscam e olham conforme os sinais. Use <b>▶ Tocar</b>, <b>⏸ Pausar</b> e arraste a linha do tempo. A animação <b>simula</b> o que foi gravado: não é vídeo da pessoa nem laudo ou diagnóstico. Para gravações de cérebro o botão fica desligado.": "<b>記録を見直す</b>で筋肉・心臓・目の記録を選び、<b>▶ リプレイ</b>をクリックします。人形がマークされた動作を再現し、心臓が記録されたリズムで鼓動し、あるいは二つの目が信号に合わせてまばたきし視線を動かします。<b>▶ 再生</b>、<b>⏸ 一時停止</b>を使い、タイムラインをドラッグしてください。アニメーションは記録内容を<b>再現</b>したもので、本人の映像でも報告書・診断でもありません。脳の記録ではボタンは無効です。",
    "Escolher o perfil de uso (quais abas aparecem)": "使用プロファイルを選ぶ（表示されるタブ）",
    "Fechei a janela e perdi as marcações": "ウィンドウを閉じてマークが消えた",
    "Instalações antigas começam em <b>Tudo</b>: nada some sem você escolher.": "以前からのインストールは<b>すべて</b>で始まります。あなたが選ばない限り何も消えません。",
    "Manual: Abertura rápida": "マニュアル：高速起動",
    "Manual: Canais em uso": "マニュアル：使用中のチャンネル",
    "Manual: Exame de músculos → Atlas muscular": "マニュアル：筋肉の検査 → 筋肉アトラス",
    "Manual: Nível Completo → Painéis em gavetas": "マニュアル：完全レベル → 引き出し式パネル",
    "Manual: Perfis de uso": "マニュアル：使用プロファイル",
    "Manual: Rever uma gravação → Replay": "マニュアル：記録を見直す → リプレイ",
    "Manual: Rever uma gravação → Replay → Músculos": "マニュアル：記録を見直す → リプレイ → 筋肉",
    "Marcar ou corrigir os movimentos do Replay (músculos)": "リプレイの動作をマーク・修正する（筋肉）",
    "Montagens de versões anteriores são convertidas sozinhas; confira só se os pontos caíram onde você esperava.": "以前のバージョンの配置は自動で変換されます。点が想定どおりの位置にあるかだけ確認してください。",
    "Na <b>tela inicial</b>, abra a caixa <b>Perfil de uso</b> e escolha <b>Cérebro</b>, <b>Músculos</b>, <b>Coração</b>, <b>Olhos</b> ou <b>Tudo</b>.": "<b>ホーム画面</b>で<b>使用プロファイル</b>のボックスを開き、<b>脳</b>、<b>筋肉</b>、<b>心臓</b>、<b>目</b>、<b>すべて</b>のいずれかを選びます。",
    "Na aba <b>Músculos</b>, escolha a <b>Vista</b>: frente, costas, lado ou uma área ampliada (rosto, antebraço e mão, perna…).": "<b>筋肉</b>タブで<b>ビュー</b>を選びます：正面、背面、側面、または拡大領域（顔、前腕と手、脚…）。",
    "Na aba <b>Músculos</b>, o desenho do corpo (frente, costas, lado e áreas ampliadas) mostra cada eletrodo como um ponto numerado. Clique em <b>Adicionar eletrodo</b> e depois no corpo: o ponto cola no lugar recomendado (ventre do músculo, referência SENIAM) ou fica onde você clicou. Durante o exame, uma mancha de calor no ponto do eletrodo mostra a intensidade medida ali.": "<b>筋肉</b>タブの体の図（正面、背面、側面、拡大領域）は、各電極を番号付きの点で示します。<b>電極を追加</b>をクリックしてから体をクリックすると、点は推奨位置（筋腹、SENIAM 基準）に吸着するか、クリックした位置に置かれます。検査中は電極の点の熱い斑点がそこで測った強さを示します。",
    "No coração, a faixa de batidas usa cor <b>e</b> forma: traço fino = regular, triângulo laranja = adiantada, retângulo vermelho = pausa maior.": "心臓では、拍の帯は色<b>と</b>形の両方を使います：細い線 = 規則的、オレンジの三角 = 早期、赤い長方形 = 長い休止。",
    "No nível Completo cada painel é uma <b>gaveta</b>: <b>▾</b> recolhe, <b>⋯</b> abre o menu (mover, tamanho padrão, fechar) e <b>×</b> fecha. Para reabrir um painel ou voltar ao arranjo original, use o botão <b>Painéis ▾</b> no alto da aba e marque-o, ou escolha <b>Restaurar o padrão</b>. A alça na borda de baixo muda a altura. O arranjo fica salvo para a próxima vez.": "完全レベルでは各パネルが<b>引き出し</b>です：<b>▾</b> で折りたたみ、<b>⋯</b> でメニュー（移動、既定サイズ、閉じる）、<b>×</b> で閉じます。パネルを再び開く、または元の配置に戻すには、タブ上部の<b>パネル ▾</b> ボタンでチェックを入れるか、<b>既定に戻す</b>を選びます。下端のハンドルで高さを変えます。配置は次回のために保存されます。",
    "Nos olhos, se os lados saírem trocados, marque <b>Inverter horizontal</b> ou <b>Inverter vertical</b>.": "目では、左右が逆に出る場合、<b>水平反転</b>または<b>垂直反転</b>にチェックを入れます。",
    "O botão ▶ Replay está apagado": "▶ リプレイのボタンが灰色",
    "O eletrodo caiu no músculo errado": "電極が違う筋肉に置かれた",
    "O perfil diz com o que você trabalha e esconde as abas que não fazem parte. Troque na <b>tela inicial</b> (caixa <b>Perfil de uso</b>) ou em <b>Sistema → Perfil de uso</b>, onde também se cria <b>Minha bancada</b> com exatamente os exames e gráficos que você quer. <b>Tudo</b> mostra o programa inteiro. Uma gravação de outro exame abre normalmente em qualquer perfil.": "プロファイルはあなたが何を扱うかを示し、それ以外のタブを隠します。<b>ホーム画面</b>（<b>使用プロファイル</b>のボックス）または<b>システム → 使用プロファイル</b>で切り替えられ、そこでは欲しい検査とグラフだけを選んだ<b>マイベンチ</b>も作れます。<b>すべて</b>はプログラム全体を表示します。別の検査の記録はどのプロファイルでも普通に開けます。",
    "O programa demora para abrir": "プログラムの起動が遅い",
    "Onde está cada eletrodo (desenho do corpo)": "各電極の位置（体の図）",
    "Os trechos nascem dos marcadores da gravação; sem marcador, as contrações detectadas aparecem como <b>a definir</b>. Clique com o botão direito num trecho e escolha <b>Trocar o movimento</b>.": "区間は記録のマーカーから生まれます。マーカーがない場合、検出された収縮は<b>未定</b>として表示されます。区間を右クリックして<b>動作を変更</b>を選びます。",
    "Para um perfil só seu, vá em <b>Sistema → Perfil de uso</b>, clique em <b>Nova…</b> (Minha bancada) e marque os exames e, no Completo, os gráficos que quer ver.": "自分専用のプロファイルは、<b>システム → 使用プロファイル</b>で<b>新規…</b>（マイベンチ）をクリックし、検査と、完全レベルでは表示したいグラフにチェックを入れます。",
    "Para uma sequência inteira, use <b>Tarefa pronta</b> (levantar o halter, abrir a porta com a chave, pegar o copo): ela entra a partir do cursor.": "一連の動作をまとめて入れるには<b>既定のタスク</b>（ダンベルを持ち上げる、鍵でドアを開ける、コップを取る）を使います。カーソル位置から挿入されます。",
    "Perfil de uso: Cérebro, Músculos, Coração, Olhos ou Tudo": "使用プロファイル：脳、筋肉、心臓、目、すべて",
    "Replay (animação da gravação)": "リプレイ（記録のアニメーション）",
    "Replay: ver a gravação como uma animação": "リプレイ：記録をアニメーションとして見る",
    "Rever uma gravação → ▶ Replay": "記録を見直す → ▶ リプレイ",
    "Surface EMG for Non-Invasive Assessment of Muscles": "Surface EMG for Non-Invasive Assessment of Muscles",
    "Só os canais em uso aparecem nas listas": "一覧には使用中のチャンネルだけが表示される",
    "Um aviso aparece quando os músculos ativos não combinam com o movimento escolhido (tríceps ativo num trecho de flexão, por exemplo). Ele é uma dica, não uma correção automática.": "活動している筋肉が選んだ動作と合わないとき（例：屈曲の区間で上腕三頭筋が活動）に注意が表示されます。これはヒントであり、自動修正ではありません。",
    "Um painel sumiu ou quero reorganizar os painéis (gavetas)": "パネルが消えた、またはパネルを並べ替えたい（引き出し）",
    "Uma aba sumiu": "タブが消えた",
    "Uma gravação de outro exame abre igual em qualquer perfil; o perfil só organiza a tela.": "別の検査の記録はどのプロファイルでも同じように開けます。プロファイルは画面を整理するだけです。",
    "Ver o Replay de uma gravação de músculos, coração ou olhos": "筋肉・心臓・目の記録のリプレイを見る",
    "Visualizar → Músculos → desenho do corpo": "表示 → 筋肉 → 体の図",
    "Volte para a coleta: as abas de fora do perfil somem e as outras ficam no lugar.": "計測に戻ります。プロファイル外のタブは消え、ほかはそのまま残ります。",
    "Vá em <b>Rever uma gravação</b> e escolha a gravação na lista: a animação só existe para exames de músculos, coração e olhos.": "<b>記録を見直す</b>へ行き、一覧から記録を選びます。アニメーションは筋肉・心臓・目の検査にだけあります。",
    "a gravação não tem marcadores de movimento nem contrações detectadas. No nível Completo, marque os trechos na linha do tempo com o botão direito.": "その記録には動作のマーカーも検出された収縮もありません。完全レベルで、タイムライン上を右クリックして区間をマークしてください。",
    "a gravação tocando como animação: a figura que se move, o coração que bate ou os olhos que piscam e olham.": "記録がアニメーションとして再生される：動く人形、鼓動する心臓、まばたきし視線を動かす目。",
    "a gravação é de cérebro ou ainda não terminou de carregar. Escolha uma gravação de músculos, coração ou olhos.": "その記録は脳のものか、まだ読み込みが終わっていません。筋肉・心臓・目の記録を選んでください。",
    "animação que refaz, a partir dos sinais gravados, o movimento marcado, o ritmo do coração ou o olhar. Simula o que foi gravado: não é vídeo nem laudo.": "記録された信号から、マークされた動作、心臓のリズム、視線を再現するアニメーション。記録内容を再現したもので、映像でも報告書でもありません。",
    "arraste-o: ao soltar perto de outro ponto recomendado ele cola nele. Numa área ampliada fica mais fácil acertar.": "ドラッグしてください。別の推奨点の近くで離すとそこに吸着します。拡大領域のほうが正確に置けます。",
    "cada eletrodo no músculo certo, com o calor da ativação aparecendo no lugar dele.": "各電極が正しい筋肉の上にあり、活動の熱がその位置に表示される。",
    "o perfil atual não a inclui. Troque para <b>Tudo</b> ou edite o seu perfil em <b>Sistema → Perfil de uso</b>.": "現在のプロファイルに含まれていません。<b>すべて</b>に切り替えるか、<b>システム → 使用プロファイル</b>でプロファイルを編集してください。",
    "o programa pergunta se há marcações não salvas ao fechar; responda <b>Salvar</b>. Se já fechou, refaça e salve.": "閉じるときに未保存のマークがあるか尋ねられます。<b>保存</b>と答えてください。すでに閉じた場合はやり直して保存してください。",
    "recomendações europeias de onde colocar os eletrodos de superfície em cada músculo (sobre o ventre do músculo, longe do tendão). O desenho do corpo cola o eletrodo nesses pontos.": "各筋肉の表面電極をどこに置くかについての欧州の推奨（筋腹の上、腱から離れた位置）。体の図は電極をこれらの点に吸着させます。",
    "só as abas do seu trabalho na tela, sem perder nenhuma gravação.": "自分の仕事に必要なタブだけが画面にあり、記録は一つも失われない。",
    "uma linha do tempo com o movimento certo em cada trecho, salva ao lado da gravação.": "各区間に正しい動作が入ったタイムラインが、記録の隣に保存される。",
}
