# -*- coding: utf-8 -*-
"""Lote "p5_ajuda": traduções pt -> zh."""
TRAD = {
    "A <b>primeira</b> abertura depois de instalar ou atualizar prepara um cache (pasta <b>.roa_cache</b>, ao lado do programa ou na pasta ROA dos dados locais do usuário) e por isso demora mais; as seguintes abrem em poucos segundos. A tela de abertura com o logo diz em palavras o que está sendo carregado. Se a demora continuar, confira se o antivírus não examina a pasta do programa a cada abertura.": "安装或更新后的<b>第一次</b>打开会准备缓存（<b>.roa_cache</b> 文件夹，位于程序旁边或用户本地数据的 ROA 文件夹中），因此时间较长；之后几秒即可打开。带标志的启动画面会用文字说明正在加载的内容。如果仍然很慢，请检查杀毒软件是否在每次打开时扫描程序文件夹。",
    "A animação <b>simula</b> o que foi gravado a partir dos sinais: não é vídeo da pessoa, e não é laudo nem diagnóstico.": "动画根据信号<b>模拟</b>所记录的内容：它不是本人的视频，也不是报告或诊断。",
    "A figura não se mexe": "人形不动",
    "Abra o Replay da gravação de músculos no nível <b>Completo</b>.": "在<b>完整</b>级别打开肌肉记录的回放。",
    "Arraste a linha do tempo para ir a um instante. Na lista ao lado, clique em um trecho, uma batida ou um evento para o tocador pular até lá.": "拖动时间线到某一时刻。在旁边的列表中点击一个片段、一次心跳或一个事件，播放器会跳到那里。",
    "Arraste o ponto para ajustar; duplo clique renomeia; <b>Delete</b> remove o selecionado.": "拖动点以调整；双击重命名；<b>Delete</b> 删除所选电极。",
    "Arraste um bloco para movê-lo e puxe a borda para esticar. <b>Dividir aqui</b> corta um trecho em dois; <b>Adicionar faixa</b> cria outra faixa para movimentos ao mesmo tempo (até quatro).": "拖动色块可移动，拉动边缘可拉长。<b>在此分割</b>把一段切成两段；<b>添加轨道</b>为同时发生的动作新建一条轨道（最多四条）。",
    "As batidas e os eventos dos olhos são os mesmos do relatório PDF; corrigi-los (nível Completo) não altera a gravação, só o arquivo do Replay ao lado dela.": "心跳和眼部事件与 PDF 报告中的相同；修正它们（完整级别）不会改变记录，只会改变记录旁边的回放文件。",
    "As listas de canais mostram só os canais <b>em uso</b> no exame escolhido. Ao rever uma gravação, as listas seguem os canais daquela gravação, não os do aparelho ligado agora.": "通道列表只显示所选检查中<b>正在使用</b>的通道。回看记录时，列表跟随该记录的通道，而不是当前连接的设备。",
    "As listas de canais mostram só os canais <b>em uso</b>: ligados e do tipo do exame (um canal marcado como coração não aparece na lista de músculos). Para mudar o tipo ou religar um canal, use <b>Filtros e Canais</b> no nível Completo. Ao rever uma gravação, as listas seguem os canais daquela gravação.": "通道列表只显示<b>正在使用</b>的通道：已开启且属于该检查类型（标记为心脏的通道不会出现在肌肉列表中）。要更改类型或重新开启通道，请在完整级别使用<b>滤波器与通道</b>。回看记录时，列表跟随该记录的通道。",
    "Clique em <b>Adicionar eletrodo</b> e depois no corpo: o ponto cola no lugar recomendado do músculo mais próximo (ventre do músculo, referência SENIAM).": "点击<b>添加电极</b>，再点击身体：电极会贴到最近肌肉的推荐位置（肌腹，SENIAM 参考）。",
    "Clique em <b>▶ Replay</b>. A janela abre com o tocador: <b>▶ Tocar</b>, <b>⏸ Pausar</b>, <b>⏮ Início</b>, a linha do tempo e o relógio.": "点击<b>▶ 回放</b>。窗口随播放器打开：<b>▶ 播放</b>、<b>⏸ 暂停</b>、<b>⏮ 开始</b>、时间线和时钟。",
    "Colocar os eletrodos no desenho do corpo": "在身体图上放置电极",
    "Ctrl+Z desfaz. Clique em <b>Salvar</b>: o arquivo movimentos.json fica ao lado da gravação e é lido da próxima vez.": "Ctrl+Z 撤销。点击<b>保存</b>：movimentos.json 文件保存在记录旁边，下次自动读取。",
    "De frente, o lado <b>direito</b> da pessoa fica à <b>esquerda</b> do desenho, como numa foto; confira o D/E no nome do músculo.": "正面视图中，本人的<b>右</b>侧位于图的<b>左</b>侧，如同照片；请核对肌肉名称中的左/右。",
    "Durante o exame, a mancha de calor no ponto do eletrodo mostra a intensidade medida ali; o anel em volta do número mostra a qualidade do sinal.": "检查过程中，电极点处的热斑显示该处测得的强度；数字周围的圆环显示信号质量。",
    "Em <b>Rever uma gravação</b>, escolha uma gravação de músculos, coração ou olhos e clique em <b>▶ Replay</b>. Uma figura refaz o movimento marcado, um coração bate no ritmo gravado ou dois olhos piscam e olham conforme os sinais. Use <b>▶ Tocar</b>, <b>⏸ Pausar</b> e arraste a linha do tempo. A animação <b>simula</b> o que foi gravado: não é vídeo da pessoa nem laudo ou diagnóstico. Para gravações de cérebro o botão fica desligado.": "在<b>回看记录</b>中选择一条肌肉、心脏或眼睛的记录，点击<b>▶ 回放</b>。人形重现标记的动作，心脏按记录的节律跳动，或两只眼睛按信号眨眼和转动。使用<b>▶ 播放</b>、<b>⏸ 暂停</b>并拖动时间线。动画<b>模拟</b>所记录的内容：不是本人的视频，也不是报告或诊断。脑部记录的该按钮不可用。",
    "Escolher o perfil de uso (quais abas aparecem)": "选择使用配置（显示哪些标签页）",
    "Fechei a janela e perdi as marcações": "我关闭了窗口，标记丢失了",
    "Instalações antigas começam em <b>Tudo</b>: nada some sem você escolher.": "旧安装从<b>全部</b>开始：没有您的选择，什么都不会消失。",
    "Manual: Abertura rápida": "手册：快速启动",
    "Manual: Canais em uso": "手册：使用中的通道",
    "Manual: Exame de músculos → Atlas muscular": "手册：肌肉检查 → 肌肉图谱",
    "Manual: Nível Completo → Painéis em gavetas": "手册：完整级别 → 抽屉式面板",
    "Manual: Perfis de uso": "手册：使用配置",
    "Manual: Rever uma gravação → Replay": "手册：回看记录 → 回放",
    "Manual: Rever uma gravação → Replay → Músculos": "手册：回看记录 → 回放 → 肌肉",
    "Marcar ou corrigir os movimentos do Replay (músculos)": "标记或修正回放中的动作（肌肉）",
    "Montagens de versões anteriores são convertidas sozinhas; confira só se os pontos caíram onde você esperava.": "旧版本的电极布局会自动转换；只需确认各点落在预期位置。",
    "Na <b>tela inicial</b>, abra a caixa <b>Perfil de uso</b> e escolha <b>Cérebro</b>, <b>Músculos</b>, <b>Coração</b>, <b>Olhos</b> ou <b>Tudo</b>.": "在<b>主屏幕</b>打开<b>使用配置</b>框，选择<b>大脑</b>、<b>肌肉</b>、<b>心脏</b>、<b>眼睛</b>或<b>全部</b>。",
    "Na aba <b>Músculos</b>, escolha a <b>Vista</b>: frente, costas, lado ou uma área ampliada (rosto, antebraço e mão, perna…).": "在<b>肌肉</b>标签页选择<b>视图</b>：正面、背面、侧面或放大区域（面部、前臂与手、腿……）。",
    "Na aba <b>Músculos</b>, o desenho do corpo (frente, costas, lado e áreas ampliadas) mostra cada eletrodo como um ponto numerado. Clique em <b>Adicionar eletrodo</b> e depois no corpo: o ponto cola no lugar recomendado (ventre do músculo, referência SENIAM) ou fica onde você clicou. Durante o exame, uma mancha de calor no ponto do eletrodo mostra a intensidade medida ali.": "在<b>肌肉</b>标签页，身体图（正面、背面、侧面和放大区域）把每个电极显示为带编号的点。点击<b>添加电极</b>，再点击身体：点会贴到推荐位置（肌腹，SENIAM 参考）或停在您点击的位置。检查过程中，电极点处的热斑显示该处测得的强度。",
    "No coração, a faixa de batidas usa cor <b>e</b> forma: traço fino = regular, triângulo laranja = adiantada, retângulo vermelho = pausa maior.": "心脏部分，心跳条同时用颜色<b>和</b>形状：细线 = 规律，橙色三角 = 提前，红色矩形 = 较长停顿。",
    "No nível Completo cada painel é uma <b>gaveta</b>: <b>▾</b> recolhe, <b>⋯</b> abre o menu (mover, tamanho padrão, fechar) e <b>×</b> fecha. Para reabrir um painel ou voltar ao arranjo original, use o botão <b>Painéis ▾</b> no alto da aba e marque-o, ou escolha <b>Restaurar o padrão</b>. A alça na borda de baixo muda a altura. O arranjo fica salvo para a próxima vez.": "在完整级别，每个面板都是一个<b>抽屉</b>：<b>▾</b> 折叠，<b>⋯</b> 打开菜单（移动、默认大小、关闭），<b>×</b> 关闭。要重新打开面板或恢复原来的布局，请使用标签页顶部的<b>面板 ▾</b> 按钮勾选它，或选择<b>恢复默认</b>。底边的把手改变高度。布局会保存到下次使用。",
    "Nos olhos, se os lados saírem trocados, marque <b>Inverter horizontal</b> ou <b>Inverter vertical</b>.": "眼睛部分，如果左右颠倒，请勾选<b>水平反转</b>或<b>垂直反转</b>。",
    "O botão ▶ Replay está apagado": "▶ 回放按钮是灰色的",
    "O eletrodo caiu no músculo errado": "电极落在了错误的肌肉上",
    "O perfil diz com o que você trabalha e esconde as abas que não fazem parte. Troque na <b>tela inicial</b> (caixa <b>Perfil de uso</b>) ou em <b>Sistema → Perfil de uso</b>, onde também se cria <b>Minha bancada</b> com exatamente os exames e gráficos que você quer. <b>Tudo</b> mostra o programa inteiro. Uma gravação de outro exame abre normalmente em qualquer perfil.": "使用配置说明您的工作内容，并隐藏不属于它的标签页。在<b>主屏幕</b>（<b>使用配置</b>框）或<b>系统 → 使用配置</b>中更改，那里还可以创建<b>我的工作台</b>，精确选择想要的检查和图表。<b>全部</b>显示整个程序。其他检查的记录在任何配置下都能正常打开。",
    "O programa demora para abrir": "程序打开很慢",
    "Onde está cada eletrodo (desenho do corpo)": "每个电极在哪里（身体图）",
    "Os trechos nascem dos marcadores da gravação; sem marcador, as contrações detectadas aparecem como <b>a definir</b>. Clique com o botão direito num trecho e escolha <b>Trocar o movimento</b>.": "片段来自记录的标记；没有标记时，检测到的收缩显示为<b>待定</b>。右键点击一个片段，选择<b>更改动作</b>。",
    "Para um perfil só seu, vá em <b>Sistema → Perfil de uso</b>, clique em <b>Nova…</b> (Minha bancada) e marque os exames e, no Completo, os gráficos que quer ver.": "要创建自己的配置，请进入<b>系统 → 使用配置</b>，点击<b>新建…</b>（我的工作台），勾选检查项目，在完整级别还可勾选想看的图表。",
    "Para uma sequência inteira, use <b>Tarefa pronta</b> (levantar o halter, abrir a porta com a chave, pegar o copo): ela entra a partir do cursor.": "要插入整套动作，请使用<b>预设任务</b>（举哑铃、用钥匙开门、拿杯子）：从光标处开始插入。",
    "Perfil de uso: Cérebro, Músculos, Coração, Olhos ou Tudo": "使用配置：大脑、肌肉、心脏、眼睛或全部",
    "Replay (animação da gravação)": "回放（记录的动画）",
    "Replay: ver a gravação como uma animação": "回放：把记录看成动画",
    "Rever uma gravação → ▶ Replay": "回看记录 → ▶ 回放",
    "Surface EMG for Non-Invasive Assessment of Muscles": "Surface EMG for Non-Invasive Assessment of Muscles",
    "Só os canais em uso aparecem nas listas": "列表中只显示正在使用的通道",
    "Um aviso aparece quando os músculos ativos não combinam com o movimento escolhido (tríceps ativo num trecho de flexão, por exemplo). Ele é uma dica, não uma correção automática.": "当活动的肌肉与所选动作不符时（例如屈曲片段中肱三头肌活动）会出现提示。它只是提示，不会自动修正。",
    "Um painel sumiu ou quero reorganizar os painéis (gavetas)": "有个面板不见了，或者我想重新排列面板（抽屉）",
    "Uma aba sumiu": "有个标签页不见了",
    "Uma gravação de outro exame abre igual em qualquer perfil; o perfil só organiza a tela.": "其他检查的记录在任何配置下都同样打开；配置只是整理屏幕。",
    "Ver o Replay de uma gravação de músculos, coração ou olhos": "观看肌肉、心脏或眼睛记录的回放",
    "Visualizar → Músculos → desenho do corpo": "查看 → 肌肉 → 身体图",
    "Volte para a coleta: as abas de fora do perfil somem e as outras ficam no lugar.": "回到采集：配置之外的标签页消失，其余保持原位。",
    "Vá em <b>Rever uma gravação</b> e escolha a gravação na lista: a animação só existe para exames de músculos, coração e olhos.": "进入<b>回看记录</b>并在列表中选择记录：动画只适用于肌肉、心脏和眼睛检查。",
    "a gravação não tem marcadores de movimento nem contrações detectadas. No nível Completo, marque os trechos na linha do tempo com o botão direito.": "该记录没有动作标记，也没有检测到收缩。在完整级别，用右键在时间线上标记片段。",
    "a gravação tocando como animação: a figura que se move, o coração que bate ou os olhos que piscam e olham.": "记录以动画播放：会动的人形、跳动的心脏或眨眼转动的眼睛。",
    "a gravação é de cérebro ou ainda não terminou de carregar. Escolha uma gravação de músculos, coração ou olhos.": "该记录是脑部记录，或尚未加载完成。请选择肌肉、心脏或眼睛的记录。",
    "animação que refaz, a partir dos sinais gravados, o movimento marcado, o ritmo do coração ou o olhar. Simula o que foi gravado: não é vídeo nem laudo.": "根据记录的信号重现标记的动作、心脏节律或视线的动画。它模拟所记录的内容：不是视频，也不是报告。",
    "arraste-o: ao soltar perto de outro ponto recomendado ele cola nele. Numa área ampliada fica mais fácil acertar.": "拖动它：在另一个推荐点附近松开时会贴上去。在放大区域更容易放准。",
    "cada eletrodo no músculo certo, com o calor da ativação aparecendo no lugar dele.": "每个电极都在正确的肌肉上，激活的热斑出现在它的位置。",
    "o perfil atual não a inclui. Troque para <b>Tudo</b> ou edite o seu perfil em <b>Sistema → Perfil de uso</b>.": "当前配置不包含它。切换到<b>全部</b>，或在<b>系统 → 使用配置</b>中编辑您的配置。",
    "o programa pergunta se há marcações não salvas ao fechar; responda <b>Salvar</b>. Se já fechou, refaça e salve.": "关闭时程序会询问是否有未保存的标记；请选择<b>保存</b>。如果已经关闭，请重做并保存。",
    "recomendações europeias de onde colocar os eletrodos de superfície em cada músculo (sobre o ventre do músculo, longe do tendão). O desenho do corpo cola o eletrodo nesses pontos.": "欧洲关于每块肌肉表面电极放置位置的建议（放在肌腹上，远离肌腱）。身体图会把电极贴到这些点上。",
    "só as abas do seu trabalho na tela, sem perder nenhuma gravação.": "屏幕上只显示您工作所需的标签页，不丢失任何记录。",
    "uma linha do tempo com o movimento certo em cada trecho, salva ao lado da gravação.": "每个片段都有正确动作的时间线，保存在记录旁边。",
}
