# -*- coding: utf-8 -*-
"""Lote "p6_figura_p8": traduções pt -> de."""
TRAD = {
    "A figura SIMULA o movimento marcado; não é o vídeo da pessoa.": "Die Figur SIMULIERT die markierte Bewegung; sie ist kein Video der Person.",
    "A figura SIMULA o movimento marcado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "Die Figur SIMULIERT die markierte Bewegung; sie ist kein Video der Person. Dies ist weder ein Befund noch eine Diagnose.",
    "Abra uma gravação de músculos, coração ou olhos para ver o Replay.": "Öffnen Sie eine Aufnahme von Muskeln, Herz oder Augen, um das Replay zu sehen.",
    "Coloca os movimentos da tarefa na linha do tempo a partir do instante atual, com o objeto preso à mão.": "Setzt die Bewegungen der Aufgabe ab dem aktuellen Zeitpunkt auf die Zeitleiste, mit dem Gegenstand in der Hand.",
    "Coração que bate no ritmo gravado, com todas as batidas na faixa.": "Ein Herz, das im aufgezeichneten Rhythmus schlägt, mit allen Schlägen auf dem Streifen.",
    "Figura articulada que refaz o movimento marcado, com os músculos acendendo conforme a gravação.": "Eine Gliederfigur, die die markierte Bewegung nachmacht; die Muskeln leuchten wie aufgezeichnet auf.",
    "Figura do movimento indisponível.": "Bewegungsfigur nicht verfügbar.",
    "Gráfico indisponível.": "Diagramm nicht verfügbar.",
    "Há músculos ativos ({0}) num trecho marcado como repouso.": "In einem als Ruhe markierten Abschnitt sind Muskeln aktiv ({0}).",
    "Inserir no cursor": "Am Cursor einfügen",
    "Inverter horizontal": "Horizontal spiegeln",
    "Inverter vertical": "Vertikal spiegeln",
    "O Replay existe para exames de músculos, coração e olhos; esta gravação é de outro tipo.": "Das Replay gibt es für Muskel-, Herz- und Augenuntersuchungen; diese Aufnahme ist von anderer Art.",
    "O coração desenhado SIMULA o ritmo gravado. Não é laudo nem diagnóstico.": "Das gezeichnete Herz SIMULIERT den aufgezeichneten Rhythmus. Dies ist weder ein Befund noch eine Diagnose.",
    "Olhos que piscam e olham conforme os sinais gravados.": "Augen, die gemäß den aufgezeichneten Signalen blinzeln und blicken.",
    "Os olhos desenhados SIMULAM as piscadas e o olhar gravados. Não é laudo nem diagnóstico.": "Die gezeichneten Augen SIMULIEREN die aufgezeichneten Lidschläge und den Blick. Dies ist weder ein Befund noch eine Diagnose.",
    "Remover este evento": "Dieses Ereignis entfernen",
    "Replay do coração — {0}": "Herz-Replay — {0}",
    "Replay do movimento — {0}": "Bewegungs-Replay — {0}",
    "Replay dos olhos — {0}": "Augen-Replay — {0}",
    "Simulação": "Simulation",
    "Tarefa pronta:": "Vorgefertigte Aufgabe:",
    "Traçado do coração (ECG)": "Herzkurve (EKG)",
    "Traçado dos olhos (horizontal e vertical)": "Augenkurven (horizontal und vertikal)",
    "Trocar a direção": "Richtung ändern",
    "Use se os olhos olham para o lado contrário do que a pessoa fez (eletrodos trocados).": "Verwenden, wenn die Augen zur entgegengesetzten Seite blicken als die Person es tat (vertauschte Elektroden).",
    "intensidade": "Intensität",
    "nenhum músculo acima de 2%": "kein Muskel über 2 %",
    "palma para baixo": "Handfläche nach unten",
    "palma para cima": "Handfläche nach oben",
    "▶ Replay": "▶ Replay",
}
