# -*- coding: utf-8 -*-
"""Lote "p6_figura_p8": traduções pt -> en."""
TRAD = {
    "A figura SIMULA o movimento marcado; não é o vídeo da pessoa.": "The figure SIMULATES the marked movement; it is not a video of the person.",
    "A figura SIMULA o movimento marcado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "The figure SIMULATES the marked movement; it is not a video of the person. This is not a medical report or a diagnosis.",
    "Abra uma gravação de músculos, coração ou olhos para ver o Replay.": "Open a muscle, heart or eye recording to see the Replay.",
    "Coloca os movimentos da tarefa na linha do tempo a partir do instante atual, com o objeto preso à mão.": "Places the task's movements on the timeline from the current instant, with the object held in the hand.",
    "Coração que bate no ritmo gravado, com todas as batidas na faixa.": "A heart that beats at the recorded rhythm, with every beat on the strip.",
    "Figura articulada que refaz o movimento marcado, com os músculos acendendo conforme a gravação.": "An articulated figure that redoes the marked movement, with the muscles lighting up as recorded.",
    "Figura do movimento indisponível.": "Movement figure unavailable.",
    "Gráfico indisponível.": "Chart unavailable.",
    "Há músculos ativos ({0}) num trecho marcado como repouso.": "There are active muscles ({0}) in a segment marked as rest.",
    "Inserir no cursor": "Insert at cursor",
    "Inverter horizontal": "Flip horizontal",
    "Inverter vertical": "Flip vertical",
    "O Replay existe para exames de músculos, coração e olhos; esta gravação é de outro tipo.": "The Replay exists for muscle, heart and eye exams; this recording is of another kind.",
    "O coração desenhado SIMULA o ritmo gravado. Não é laudo nem diagnóstico.": "The drawn heart SIMULATES the recorded rhythm. This is not a medical report or a diagnosis.",
    "Olhos que piscam e olham conforme os sinais gravados.": "Eyes that blink and look according to the recorded signals.",
    "Os olhos desenhados SIMULAM as piscadas e o olhar gravados. Não é laudo nem diagnóstico.": "The drawn eyes SIMULATE the recorded blinks and gaze. This is not a medical report or a diagnosis.",
    "Remover este evento": "Remove this event",
    "Replay do coração — {0}": "Heart replay — {0}",
    "Replay do movimento — {0}": "Movement replay — {0}",
    "Replay dos olhos — {0}": "Eye replay — {0}",
    "Simulação": "Simulation",
    "Tarefa pronta:": "Ready-made task:",
    "Traçado do coração (ECG)": "Heart trace (ECG)",
    "Traçado dos olhos (horizontal e vertical)": "Eye traces (horizontal and vertical)",
    "Trocar a direção": "Change the direction",
    "Use se os olhos olham para o lado contrário do que a pessoa fez (eletrodos trocados).": "Use it if the eyes look to the opposite side of what the person did (swapped electrodes).",
    "intensidade": "intensity",
    "nenhum músculo acima de 2%": "no muscle above 2%",
    "palma para baixo": "palm down",
    "palma para cima": "palm up",
    "▶ Replay": "▶ Replay",
}
