# -*- coding: utf-8 -*-
"""Lote "p6_figura_p8": traduções pt -> es."""
TRAD = {
    "A figura SIMULA o movimento marcado; não é o vídeo da pessoa.": "La figura SIMULA el movimiento marcado; no es el vídeo de la persona.",
    "A figura SIMULA o movimento marcado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "La figura SIMULA el movimiento marcado; no es un vídeo de la persona. No es un informe médico ni un diagnóstico.",
    "Abra uma gravação de músculos, coração ou olhos para ver o Replay.": "Abra una grabación de músculos, corazón u ojos para ver la Reproducción.",
    "Coloca os movimentos da tarefa na linha do tempo a partir do instante atual, com o objeto preso à mão.": "Coloca los movimientos de la tarea en la línea de tiempo a partir del instante actual, con el objeto sujeto en la mano.",
    "Coração que bate no ritmo gravado, com todas as batidas na faixa.": "Un corazón que late al ritmo grabado, con todos los latidos en la franja.",
    "Figura articulada que refaz o movimento marcado, com os músculos acendendo conforme a gravação.": "Una figura articulada que repite el movimiento marcado, con los músculos encendiéndose según la grabación.",
    "Figura do movimento indisponível.": "Figura del movimiento no disponible.",
    "Gráfico indisponível.": "Gráfico no disponible.",
    "Há músculos ativos ({0}) num trecho marcado como repouso.": "Hay músculos activos ({0}) en un tramo marcado como reposo.",
    "Inserir no cursor": "Insertar en el cursor",
    "Inverter horizontal": "Invertir horizontal",
    "Inverter vertical": "Invertir vertical",
    "O Replay existe para exames de músculos, coração e olhos; esta gravação é de outro tipo.": "La Reproducción existe para exámenes de músculos, corazón y ojos; esta grabación es de otro tipo.",
    "O coração desenhado SIMULA o ritmo gravado. Não é laudo nem diagnóstico.": "El corazón dibujado SIMULA el ritmo grabado. No es un informe médico ni un diagnóstico.",
    "Olhos que piscam e olham conforme os sinais gravados.": "Ojos que parpadean y miran según las señales grabadas.",
    "Os olhos desenhados SIMULAM as piscadas e o olhar gravados. Não é laudo nem diagnóstico.": "Los ojos dibujados SIMULAN los parpadeos y la mirada grabados. No es un informe médico ni un diagnóstico.",
    "Remover este evento": "Quitar este evento",
    "Replay do coração — {0}": "Reproducción del corazón — {0}",
    "Replay do movimento — {0}": "Reproducción del movimiento — {0}",
    "Replay dos olhos — {0}": "Reproducción de los ojos — {0}",
    "Simulação": "Simulación",
    "Tarefa pronta:": "Tarea predefinida:",
    "Traçado do coração (ECG)": "Trazado del corazón (ECG)",
    "Traçado dos olhos (horizontal e vertical)": "Trazados de los ojos (horizontal y vertical)",
    "Trocar a direção": "Cambiar la dirección",
    "Use se os olhos olham para o lado contrário do que a pessoa fez (eletrodos trocados).": "Úselo si los ojos miran hacia el lado contrario de lo que hizo la persona (electrodos intercambiados).",
    "intensidade": "intensidad",
    "nenhum músculo acima de 2%": "ningún músculo por encima del 2%",
    "palma para baixo": "palma hacia abajo",
    "palma para cima": "palma hacia arriba",
    "▶ Replay": "▶ Reproducción",
}
