# -*- coding: utf-8 -*-
"""Lote "p6_figura_p8": traduções pt -> fr."""
TRAD = {
    "A figura SIMULA o movimento marcado; não é o vídeo da pessoa.": "La figure SIMULE le mouvement marqué ; ce n'est pas la vidéo de la personne.",
    "A figura SIMULA o movimento marcado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "La figure SIMULE le mouvement marqué ; ce n'est pas une vidéo de la personne. Ce n'est ni un compte rendu médical ni un diagnostic.",
    "Abra uma gravação de músculos, coração ou olhos para ver o Replay.": "Ouvrez un enregistrement de muscles, de cœur ou d'yeux pour voir le Replay.",
    "Coloca os movimentos da tarefa na linha do tempo a partir do instante atual, com o objeto preso à mão.": "Place les mouvements de la tâche sur la ligne de temps à partir de l'instant actuel, l'objet tenu dans la main.",
    "Coração que bate no ritmo gravado, com todas as batidas na faixa.": "Un cœur qui bat au rythme enregistré, avec tous les battements sur la bande.",
    "Figura articulada que refaz o movimento marcado, com os músculos acendendo conforme a gravação.": "Une figure articulée qui refait le mouvement marqué, les muscles s'allumant selon l'enregistrement.",
    "Figura do movimento indisponível.": "Figure du mouvement indisponible.",
    "Gráfico indisponível.": "Graphique indisponible.",
    "Há músculos ativos ({0}) num trecho marcado como repouso.": "Des muscles sont actifs ({0}) dans un segment marqué comme repos.",
    "Inserir no cursor": "Insérer au curseur",
    "Inverter horizontal": "Inverser l'horizontal",
    "Inverter vertical": "Inverser le vertical",
    "O Replay existe para exames de músculos, coração e olhos; esta gravação é de outro tipo.": "Le Replay existe pour les examens des muscles, du cœur et des yeux ; cet enregistrement est d'un autre type.",
    "O coração desenhado SIMULA o ritmo gravado. Não é laudo nem diagnóstico.": "Le cœur dessiné SIMULE le rythme enregistré. Ce n'est ni un compte rendu médical ni un diagnostic.",
    "Olhos que piscam e olham conforme os sinais gravados.": "Des yeux qui clignent et regardent selon les signaux enregistrés.",
    "Os olhos desenhados SIMULAM as piscadas e o olhar gravados. Não é laudo nem diagnóstico.": "Les yeux dessinés SIMULENT les clignements et le regard enregistrés. Ce n'est ni un compte rendu médical ni un diagnostic.",
    "Remover este evento": "Supprimer cet événement",
    "Replay do coração — {0}": "Replay du cœur — {0}",
    "Replay do movimento — {0}": "Replay du mouvement — {0}",
    "Replay dos olhos — {0}": "Replay des yeux — {0}",
    "Simulação": "Simulation",
    "Tarefa pronta:": "Tâche prête :",
    "Traçado do coração (ECG)": "Tracé du cœur (ECG)",
    "Traçado dos olhos (horizontal e vertical)": "Tracés des yeux (horizontal et vertical)",
    "Trocar a direção": "Changer la direction",
    "Use se os olhos olham para o lado contrário do que a pessoa fez (eletrodos trocados).": "À utiliser si les yeux regardent du côté opposé à ce que la personne a fait (électrodes inversées).",
    "intensidade": "intensité",
    "nenhum músculo acima de 2%": "aucun muscle au-dessus de 2 %",
    "palma para baixo": "paume vers le bas",
    "palma para cima": "paume vers le haut",
    "▶ Replay": "▶ Replay",
}
