# -*- coding: utf-8 -*-
"""Lote "p6_figura_p8": traduções pt -> it."""
TRAD = {
    "A figura SIMULA o movimento marcado; não é o vídeo da pessoa.": "La figura SIMULA il movimento marcato; non è il video della persona.",
    "A figura SIMULA o movimento marcado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "La figura SIMULA il movimento marcato; non è un video della persona. Non è un referto né una diagnosi.",
    "Abra uma gravação de músculos, coração ou olhos para ver o Replay.": "Apri una registrazione di muscoli, cuore o occhi per vedere il Replay.",
    "Coloca os movimentos da tarefa na linha do tempo a partir do instante atual, com o objeto preso à mão.": "Inserisce i movimenti del compito nella linea del tempo a partire dall'istante attuale, con l'oggetto tenuto in mano.",
    "Coração que bate no ritmo gravado, com todas as batidas na faixa.": "Un cuore che batte al ritmo registrato, con tutti i battiti sulla striscia.",
    "Figura articulada que refaz o movimento marcado, com os músculos acendendo conforme a gravação.": "Una figura articolata che ripete il movimento marcato, con i muscoli che si accendono come registrato.",
    "Figura do movimento indisponível.": "Figura del movimento non disponibile.",
    "Gráfico indisponível.": "Grafico non disponibile.",
    "Há músculos ativos ({0}) num trecho marcado como repouso.": "Ci sono muscoli attivi ({0}) in un tratto marcato come riposo.",
    "Inserir no cursor": "Inserisci al cursore",
    "Inverter horizontal": "Inverti orizzontale",
    "Inverter vertical": "Inverti verticale",
    "O Replay existe para exames de músculos, coração e olhos; esta gravação é de outro tipo.": "Il Replay esiste per gli esami di muscoli, cuore e occhi; questa registrazione è di un altro tipo.",
    "O coração desenhado SIMULA o ritmo gravado. Não é laudo nem diagnóstico.": "Il cuore disegnato SIMULA il ritmo registrato. Non è un referto né una diagnosi.",
    "Olhos que piscam e olham conforme os sinais gravados.": "Occhi che sbattono le palpebre e guardano secondo i segnali registrati.",
    "Os olhos desenhados SIMULAM as piscadas e o olhar gravados. Não é laudo nem diagnóstico.": "Gli occhi disegnati SIMULANO gli ammiccamenti e lo sguardo registrati. Non è un referto né una diagnosi.",
    "Remover este evento": "Rimuovi questo evento",
    "Replay do coração — {0}": "Replay del cuore — {0}",
    "Replay do movimento — {0}": "Replay del movimento — {0}",
    "Replay dos olhos — {0}": "Replay degli occhi — {0}",
    "Simulação": "Simulazione",
    "Tarefa pronta:": "Compito predefinito:",
    "Traçado do coração (ECG)": "Tracciato del cuore (ECG)",
    "Traçado dos olhos (horizontal e vertical)": "Tracciati degli occhi (orizzontale e verticale)",
    "Trocar a direção": "Cambia la direzione",
    "Use se os olhos olham para o lado contrário do que a pessoa fez (eletrodos trocados).": "Usalo se gli occhi guardano dal lato opposto a quello che la persona ha fatto (elettrodi scambiati).",
    "intensidade": "intensità",
    "nenhum músculo acima de 2%": "nessun muscolo sopra il 2%",
    "palma para baixo": "palmo in giù",
    "palma para cima": "palmo in su",
    "▶ Replay": "▶ Replay",
}
