# -*- coding: utf-8 -*-
"""Lote "p6_figura_p8": traduções pt -> ja."""
TRAD = {
    "A figura SIMULA o movimento marcado; não é o vídeo da pessoa.": "この人物像は、マークした動きをシミュレーションしたものです。本人の映像ではありません。",
    "A figura SIMULA o movimento marcado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "この人物像は、マークした動きをシミュレーションしたものです。本人の映像ではなく、診断書でも診断でもありません。",
    "Abra uma gravação de músculos, coração ou olhos para ver o Replay.": "リプレイを見るには、筋肉・心臓・目の記録を開いてください。",
    "Coloca os movimentos da tarefa na linha do tempo a partir do instante atual, com o objeto preso à mão.": "現在の時刻から、タスクの動きを物を手に持った状態でタイムラインに配置します。",
    "Coração que bate no ritmo gravado, com todas as batidas na faixa.": "記録されたリズムで拍動する心臓。すべての拍がバンドに表示されます。",
    "Figura articulada que refaz o movimento marcado, com os músculos acendendo conforme a gravação.": "マークした動きを再現する関節付きの人物像。筋肉は記録どおりに光ります。",
    "Figura do movimento indisponível.": "動きの人物像は利用できません。",
    "Gráfico indisponível.": "グラフは利用できません。",
    "Há músculos ativos ({0}) num trecho marcado como repouso.": "休息としてマークした区間に活動中の筋肉（{0}）があります。",
    "Inserir no cursor": "カーソル位置に挿入",
    "Inverter horizontal": "水平反転",
    "Inverter vertical": "垂直反転",
    "O Replay existe para exames de músculos, coração e olhos; esta gravação é de outro tipo.": "リプレイは筋肉・心臓・目の検査用です。この記録は別の種類です。",
    "O coração desenhado SIMULA o ritmo gravado. Não é laudo nem diagnóstico.": "描かれた心臓は、記録されたリズムをシミュレーションしたものです。診断書でも診断でもありません。",
    "Olhos que piscam e olham conforme os sinais gravados.": "記録された信号に合わせてまばたきし、視線を動かす目。",
    "Os olhos desenhados SIMULAM as piscadas e o olhar gravados. Não é laudo nem diagnóstico.": "描かれた目は、記録されたまばたきと視線をシミュレーションしたものです。診断書でも診断でもありません。",
    "Remover este evento": "このイベントを削除",
    "Replay do coração — {0}": "心臓のリプレイ — {0}",
    "Replay do movimento — {0}": "動きのリプレイ — {0}",
    "Replay dos olhos — {0}": "目のリプレイ — {0}",
    "Simulação": "シミュレーション",
    "Tarefa pronta:": "既定のタスク：",
    "Traçado do coração (ECG)": "心臓の波形（ECG）",
    "Traçado dos olhos (horizontal e vertical)": "目の波形（水平・垂直）",
    "Trocar a direção": "方向を変更",
    "Use se os olhos olham para o lado contrário do que a pessoa fez (eletrodos trocados).": "本人の動きと反対側を見ている場合（電極の入れ替わり）に使います。",
    "intensidade": "強さ",
    "nenhum músculo acima de 2%": "2% を超える筋肉はありません",
    "palma para baixo": "手のひらを下に",
    "palma para cima": "手のひらを上に",
    "▶ Replay": "▶ リプレイ",
}
