# -*- coding: utf-8 -*-
"""Lote "p6_figura_p8": traduções pt -> ru."""
TRAD = {
    "A figura SIMULA o movimento marcado; não é o vídeo da pessoa.": "Фигура ИМИТИРУЕТ отмеченное движение; это не видео человека.",
    "A figura SIMULA o movimento marcado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "Фигура ИМИТИРУЕТ отмеченное движение; это не видео человека. Это не заключение и не диагноз.",
    "Abra uma gravação de músculos, coração ou olhos para ver o Replay.": "Откройте запись мышц, сердца или глаз, чтобы увидеть воспроизведение.",
    "Coloca os movimentos da tarefa na linha do tempo a partir do instante atual, com o objeto preso à mão.": "Размещает движения задания на шкале времени начиная с текущего момента, с предметом в руке.",
    "Coração que bate no ritmo gravado, com todas as batidas na faixa.": "Сердце, бьющееся в записанном ритме; все удары показаны на полосе.",
    "Figura articulada que refaz o movimento marcado, com os músculos acendendo conforme a gravação.": "Шарнирная фигура, повторяющая отмеченное движение; мышцы подсвечиваются, как записано.",
    "Figura do movimento indisponível.": "Фигура движения недоступна.",
    "Gráfico indisponível.": "График недоступен.",
    "Há músculos ativos ({0}) num trecho marcado como repouso.": "В участке, отмеченном как покой, есть активные мышцы ({0}).",
    "Inserir no cursor": "Вставить у курсора",
    "Inverter horizontal": "Отразить по горизонтали",
    "Inverter vertical": "Отразить по вертикали",
    "O Replay existe para exames de músculos, coração e olhos; esta gravação é de outro tipo.": "Воспроизведение есть для обследований мышц, сердца и глаз; эта запись другого типа.",
    "O coração desenhado SIMULA o ritmo gravado. Não é laudo nem diagnóstico.": "Нарисованное сердце ИМИТИРУЕТ записанный ритм. Это не заключение и не диагноз.",
    "Olhos que piscam e olham conforme os sinais gravados.": "Глаза, которые моргают и смотрят в соответствии с записанными сигналами.",
    "Os olhos desenhados SIMULAM as piscadas e o olhar gravados. Não é laudo nem diagnóstico.": "Нарисованные глаза ИМИТИРУЮТ записанные моргания и взгляд. Это не заключение и не диагноз.",
    "Remover este evento": "Удалить это событие",
    "Replay do coração — {0}": "Воспроизведение сердца — {0}",
    "Replay do movimento — {0}": "Воспроизведение движения — {0}",
    "Replay dos olhos — {0}": "Воспроизведение глаз — {0}",
    "Simulação": "Имитация",
    "Tarefa pronta:": "Готовое задание:",
    "Traçado do coração (ECG)": "Кривая сердца (ЭКГ)",
    "Traçado dos olhos (horizontal e vertical)": "Кривые глаз (горизонталь и вертикаль)",
    "Trocar a direção": "Изменить направление",
    "Use se os olhos olham para o lado contrário do que a pessoa fez (eletrodos trocados).": "Используйте, если глаза смотрят в противоположную сторону от того, что делал человек (электроды перепутаны).",
    "intensidade": "интенсивность",
    "nenhum músculo acima de 2%": "нет мышц выше 2%",
    "palma para baixo": "ладонь вниз",
    "palma para cima": "ладонь вверх",
    "▶ Replay": "▶ Воспроизведение",
}
