# -*- coding: utf-8 -*-
"""Lote "p6_figura_p8": traduções pt -> zh."""
TRAD = {
    "A figura SIMULA o movimento marcado; não é o vídeo da pessoa.": "该人像仅是对所标记动作的模拟，并非本人的视频。",
    "A figura SIMULA o movimento marcado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "该人像仅是对所标记动作的模拟，并非本人的视频。这不是诊断报告，也不是诊断。",
    "Abra uma gravação de músculos, coração ou olhos para ver o Replay.": "请打开一条肌肉、心脏或眼睛的记录以查看回放。",
    "Coloca os movimentos da tarefa na linha do tempo a partir do instante atual, com o objeto preso à mão.": "从当前时刻起，把该任务的动作放到时间线上，物体握在手中。",
    "Coração que bate no ritmo gravado, com todas as batidas na faixa.": "按所记录的节律跳动的心脏，所有心跳都显示在条带上。",
    "Figura articulada que refaz o movimento marcado, com os músculos acendendo conforme a gravação.": "按所标记动作活动的关节人像，肌肉按记录依次点亮。",
    "Figura do movimento indisponível.": "动作人像不可用。",
    "Gráfico indisponível.": "图表不可用。",
    "Há músculos ativos ({0}) num trecho marcado como repouso.": "在标记为休息的片段中有活动的肌肉（{0}）。",
    "Inserir no cursor": "在光标处插入",
    "Inverter horizontal": "水平反转",
    "Inverter vertical": "垂直反转",
    "O Replay existe para exames de músculos, coração e olhos; esta gravação é de outro tipo.": "回放仅适用于肌肉、心脏和眼睛检查；这条记录属于其他类型。",
    "O coração desenhado SIMULA o ritmo gravado. Não é laudo nem diagnóstico.": "所绘的心脏仅是对所记录节律的模拟。这不是诊断报告，也不是诊断。",
    "Olhos que piscam e olham conforme os sinais gravados.": "按所记录的信号眨眼并转动目光的眼睛。",
    "Os olhos desenhados SIMULAM as piscadas e o olhar gravados. Não é laudo nem diagnóstico.": "所绘的眼睛仅是对所记录的眨眼和目光的模拟。这不是诊断报告，也不是诊断。",
    "Remover este evento": "删除此事件",
    "Replay do coração — {0}": "心脏回放 — {0}",
    "Replay do movimento — {0}": "动作回放 — {0}",
    "Replay dos olhos — {0}": "眼睛回放 — {0}",
    "Simulação": "模拟",
    "Tarefa pronta:": "预设任务：",
    "Traçado do coração (ECG)": "心脏曲线（ECG）",
    "Traçado dos olhos (horizontal e vertical)": "眼睛曲线（水平与垂直）",
    "Trocar a direção": "更改方向",
    "Use se os olhos olham para o lado contrário do que a pessoa fez (eletrodos trocados).": "如果眼睛看向与本人实际相反的一侧（电极接反），请使用此项。",
    "intensidade": "强度",
    "nenhum músculo acima de 2%": "没有肌肉超过 2%",
    "palma para baixo": "掌心向下",
    "palma para cima": "掌心向上",
    "▶ Replay": "▶ 回放",
}
