# -*- coding: utf-8 -*-
"""Lote "replay_p6p7": traduções pt -> de. Preencha os valores vazios."""
TRAD = {
    "(corrigida à mão)": "(von Hand korrigiert)",
    "(corrigido à mão)": "(von Hand korrigiert)",
    "A animação SIMULA o que foi gravado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "Die Animation SIMULIERT das Aufgezeichnete; sie ist kein Video der Person. Kein Befund und keine Diagnose.",
    "A definir": "Noch festzulegen",
    "Abrir a mão": "Hand öffnen",
    "Abrir mão": "Hand öffnen",
    "Adicionar batida aqui": "Schlag hier hinzufügen",
    "Adicionar faixa": "Spur hinzufügen",
    "Apagar": "Löschen",
    "Arraste para ir a um instante da gravação.": "Ziehen, um zu einem Zeitpunkt der Aufzeichnung zu springen.",
    "Desfazer": "Rückgängig",
    "Dividir aqui": "Hier teilen",
    "Ext. cotovelo": "Ext. Ellenbogen",
    "Ext. ombro": "Ext. Schulter",
    "Ext. punho": "Ext. Handgelenk",
    "Extensão do cotovelo": "Ellenbogenextension",
    "Extensão do ombro": "Schulterextension",
    "Extensão do punho": "Handgelenkextension",
    "Faixa {0}": "Spur {0}",
    "Fechar a mão": "Hand schließen",
    "Fechar mão": "Hand schließen",
    "Flex. cotovelo": "Flex. Ellenbogen",
    "Flex. ombro": "Flex. Schulter",
    "Flex. punho": "Flex. Handgelenk",
    "Flexão do cotovelo": "Ellenbogenflexion",
    "Flexão do ombro": "Schulterflexion",
    "Flexão do punho": "Handgelenkflexion",
    "Grava as marcações ao lado da gravação.": "Speichert die Markierungen neben der Aufzeichnung.",
    "Há marcações não salvas. Salvar antes de fechar?": "Es gibt ungespeicherte Markierungen. Vor dem Schließen speichern?",
    "Isto não é laudo nem diagnóstico.": "Dies ist kein Befund und keine Diagnose.",
    "Marcar como batida adiantada": "Als verfrühten Schlag markieren",
    "Marcar como batida regular": "Als regelmäßigen Schlag markieren",
    "Marcar como pausa maior": "Als längere Pause markieren",
    "Nenhum trecho de movimento marcado nesta gravação.": "In dieser Aufzeichnung ist kein Bewegungsabschnitt markiert.",
    "Nenhuma gravação carregada.": "Keine Aufzeichnung geladen.",
    "Nenhuma piscada ou movimento dos olhos encontrado.": "Kein Lidschlag und keine Augenbewegung gefunden.",
    "Novo trecho aqui": "Neuer Abschnitt hier",
    "Não foi possível salvar: {0}": "Speichern nicht möglich: {0}",
    "Os músculos ativos ({0}) não combinam com o movimento escolhido ({1}); esperado: {2}.": "Die aktiven Muskeln ({0}) passen nicht zur gewählten Bewegung ({1}); erwartet: {2}.",
    "Pinça": "Pinzettengriff",
    "Pronação": "Pronation",
    "Pronação (palma para baixo)": "Pronation (Handfläche nach unten)",
    "Protocolo: fim": "Protokoll: Ende",
    "Protocolo: início": "Protokoll: Anfang",
    "Refazer": "Wiederherstellen",
    "Remover batida": "Schlag entfernen",
    "Remover faixa": "Spur entfernen",
    "Repetir": "Wiederholen",
    "Replay": "Replay",
    "Supinação": "Supination",
    "Supinação (palma para cima)": "Supination (Handfläche nach oben)",
    "Toca ou pausa o replay (barra de espaço).": "Startet oder pausiert das Replay (Leertaste).",
    "Todas as batidas foram regulares.": "Alle Schläge waren regelmäßig.",
    "Trocar o movimento": "Bewegung wechseln",
    "Velocidade do replay (não muda a gravação).": "Replay-Geschwindigkeit (ändert die Aufzeichnung nicht).",
    "Volta para o começo da gravação.": "Springt zum Anfang der Aufzeichnung zurück.",
    "adiantada": "verfrüht",
    "aguardando a primeira batida": "warte auf den ersten Schlag",
    "baixo": "unten",
    "batida adiantada": "verfrühter Schlag",
    "batida regular": "regelmäßiger Schlag",
    "bpm em média: —": "bpm im Mittel: —",
    "cima": "oben",
    "direita": "rechts",
    "esquerda": "links",
    "faixa {0}": "Spur {0}",
    "nenhuma adiantada": "keine verfrühten",
    "nenhuma batida": "keine Schläge",
    "nenhuma pausa": "keine Pausen",
    "olhando para a direita": "blickt nach rechts",
    "olhando para a esquerda": "blickt nach links",
    "olhando para baixo": "blickt nach unten",
    "olhando para cima": "blickt nach oben",
    "olhando para frente": "blickt geradeaus",
    "pausa": "Pause",
    "pausa maior": "längere Pause",
    "piscadas: {0} · para os lados: {1} · para cima ou baixo: {2}": "Lidschläge: {0} · zur Seite: {1} · nach oben oder unten: {2}",
    "piscando": "blinzelt",
    "regular": "regelmäßig",
    "{0} adiantada": "{0} verfrüht",
    "{0} adiantadas": "{0} verfrüht",
    "{0} batida": "{0} Schlag",
    "{0} batidas": "{0} Schläge",
    "{0} bpm em média": "{0} bpm im Mittel",
    "{0} evento": "{0} Ereignis",
    "{0} ficou olhando para a direita": "{0} hält den Blick nach rechts",
    "{0} ficou olhando para a esquerda": "{0} hält den Blick nach links",
    "{0} ficou olhando para baixo": "{0} hält den Blick nach unten",
    "{0} ficou olhando para cima": "{0} hält den Blick nach oben",
    "{0} ficou olhando para frente": "{0} hält den Blick geradeaus",
    "{0} moveu os olhos": "{0} bewegt die Augen",
    "{0} olhou para a direita": "{0} blickt nach rechts",
    "{0} olhou para a esquerda": "{0} blickt nach links",
    "{0} olhou para baixo": "{0} blickt nach unten",
    "{0} olhou para cima": "{0} blickt nach oben",
    "{0} pausa": "{0} Pause",
    "{0} pausas": "{0} Pausen",
    "{0} piscou": "{0} blinzelt",
    "{0} por {1} s": "{0} für {1} s",
    "⏮ Início": "⏮ Anfang",
    "⏸ Pausar": "⏸ Pause",
    "▶ Tocar": "▶ Abspielen",
}
