# -*- coding: utf-8 -*-
"""Lote "replay_p6p7": traduções pt -> en. Preencha os valores vazios."""
TRAD = {
    "(corrigida à mão)": "(hand-corrected)",
    "(corrigido à mão)": "(hand-corrected)",
    "A animação SIMULA o que foi gravado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "The animation SIMULATES what was recorded; it is not a video of the person. Not a medical report nor a diagnosis.",
    "A definir": "To be defined",
    "Abrir a mão": "Open the hand",
    "Abrir mão": "Open hand",
    "Adicionar batida aqui": "Add beat here",
    "Adicionar faixa": "Add track",
    "Apagar": "Delete",
    "Arraste para ir a um instante da gravação.": "Drag to go to a moment in the recording.",
    "Desfazer": "Undo",
    "Dividir aqui": "Split here",
    "Ext. cotovelo": "Elbow ext.",
    "Ext. ombro": "Shoulder ext.",
    "Ext. punho": "Wrist ext.",
    "Extensão do cotovelo": "Elbow extension",
    "Extensão do ombro": "Shoulder extension",
    "Extensão do punho": "Wrist extension",
    "Faixa {0}": "Track {0}",
    "Fechar a mão": "Close the hand",
    "Fechar mão": "Close hand",
    "Flex. cotovelo": "Elbow flex.",
    "Flex. ombro": "Shoulder flex.",
    "Flex. punho": "Wrist flex.",
    "Flexão do cotovelo": "Elbow flexion",
    "Flexão do ombro": "Shoulder flexion",
    "Flexão do punho": "Wrist flexion",
    "Grava as marcações ao lado da gravação.": "Saves the marks next to the recording.",
    "Há marcações não salvas. Salvar antes de fechar?": "There are unsaved marks. Save before closing?",
    "Isto não é laudo nem diagnóstico.": "This is not a medical report nor a diagnosis.",
    "Marcar como batida adiantada": "Mark as early beat",
    "Marcar como batida regular": "Mark as regular beat",
    "Marcar como pausa maior": "Mark as longer pause",
    "Nenhum trecho de movimento marcado nesta gravação.": "No movement segment marked in this recording.",
    "Nenhuma gravação carregada.": "No recording loaded.",
    "Nenhuma piscada ou movimento dos olhos encontrado.": "No blink or eye movement found.",
    "Novo trecho aqui": "New segment here",
    "Não foi possível salvar: {0}": "Could not save: {0}",
    "Os músculos ativos ({0}) não combinam com o movimento escolhido ({1}); esperado: {2}.": "The active muscles ({0}) do not match the chosen movement ({1}); expected: {2}.",
    "Pinça": "Pinch",
    "Pronação": "Pronation",
    "Pronação (palma para baixo)": "Pronation (palm down)",
    "Protocolo: fim": "Protocol: end",
    "Protocolo: início": "Protocol: start",
    "Refazer": "Redo",
    "Remover batida": "Remove beat",
    "Remover faixa": "Remove track",
    "Repetir": "Repeat",
    "Replay": "Replay",
    "Supinação": "Supination",
    "Supinação (palma para cima)": "Supination (palm up)",
    "Toca ou pausa o replay (barra de espaço).": "Plays or pauses the replay (space bar).",
    "Todas as batidas foram regulares.": "All beats were regular.",
    "Trocar o movimento": "Change movement",
    "Velocidade do replay (não muda a gravação).": "Replay speed (does not change the recording).",
    "Volta para o começo da gravação.": "Goes back to the start of the recording.",
    "adiantada": "early",
    "aguardando a primeira batida": "waiting for the first beat",
    "baixo": "down",
    "batida adiantada": "early beat",
    "batida regular": "regular beat",
    "bpm em média: —": "bpm on average: —",
    "cima": "up",
    "direita": "right",
    "esquerda": "left",
    "faixa {0}": "track {0}",
    "nenhuma adiantada": "no early beats",
    "nenhuma batida": "no beats",
    "nenhuma pausa": "no pauses",
    "olhando para a direita": "looking right",
    "olhando para a esquerda": "looking left",
    "olhando para baixo": "looking down",
    "olhando para cima": "looking up",
    "olhando para frente": "looking straight ahead",
    "pausa": "pause",
    "pausa maior": "longer pause",
    "piscadas: {0} · para os lados: {1} · para cima ou baixo: {2}": "blinks: {0} · sideways: {1} · up or down: {2}",
    "piscando": "blinking",
    "regular": "regular",
    "{0} adiantada": "{0} early",
    "{0} adiantadas": "{0} early",
    "{0} batida": "{0} beat",
    "{0} batidas": "{0} beats",
    "{0} bpm em média": "{0} bpm on average",
    "{0} evento": "{0} event",
    "{0} ficou olhando para a direita": "{0} kept looking right",
    "{0} ficou olhando para a esquerda": "{0} kept looking left",
    "{0} ficou olhando para baixo": "{0} kept looking down",
    "{0} ficou olhando para cima": "{0} kept looking up",
    "{0} ficou olhando para frente": "{0} kept looking straight ahead",
    "{0} moveu os olhos": "{0} moved the eyes",
    "{0} olhou para a direita": "{0} looked right",
    "{0} olhou para a esquerda": "{0} looked left",
    "{0} olhou para baixo": "{0} looked down",
    "{0} olhou para cima": "{0} looked up",
    "{0} pausa": "{0} pause",
    "{0} pausas": "{0} pauses",
    "{0} piscou": "{0} blinked",
    "{0} por {1} s": "{0} for {1} s",
    "⏮ Início": "⏮ Start",
    "⏸ Pausar": "⏸ Pause",
    "▶ Tocar": "▶ Play",
}
