# -*- coding: utf-8 -*-
"""Lote "replay_p6p7": traduções pt -> es. Preencha os valores vazios."""
TRAD = {
    "(corrigida à mão)": "(corregido a mano)",
    "(corrigido à mão)": "(corregido a mano)",
    "A animação SIMULA o que foi gravado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "La animación SIMULA lo que se grabó; no es un vídeo de la persona. No es un informe médico ni un diagnóstico.",
    "A definir": "Por definir",
    "Abrir a mão": "Abrir la mano",
    "Abrir mão": "Abrir mano",
    "Adicionar batida aqui": "Añadir latido aquí",
    "Adicionar faixa": "Añadir pista",
    "Apagar": "Borrar",
    "Arraste para ir a um instante da gravação.": "Arrastre para ir a un instante de la grabación.",
    "Desfazer": "Deshacer",
    "Dividir aqui": "Dividir aquí",
    "Ext. cotovelo": "Ext. codo",
    "Ext. ombro": "Ext. hombro",
    "Ext. punho": "Ext. muñeca",
    "Extensão do cotovelo": "Extensión de codo",
    "Extensão do ombro": "Extensión de hombro",
    "Extensão do punho": "Extensión de muñeca",
    "Faixa {0}": "Pista {0}",
    "Fechar a mão": "Cerrar la mano",
    "Fechar mão": "Cerrar mano",
    "Flex. cotovelo": "Flex. codo",
    "Flex. ombro": "Flex. hombro",
    "Flex. punho": "Flex. muñeca",
    "Flexão do cotovelo": "Flexión de codo",
    "Flexão do ombro": "Flexión de hombro",
    "Flexão do punho": "Flexión de muñeca",
    "Grava as marcações ao lado da gravação.": "Guarda las marcas junto a la grabación.",
    "Há marcações não salvas. Salvar antes de fechar?": "Hay marcas sin guardar. ¿Guardar antes de cerrar?",
    "Isto não é laudo nem diagnóstico.": "Esto no es un informe médico ni un diagnóstico.",
    "Marcar como batida adiantada": "Marcar como latido adelantado",
    "Marcar como batida regular": "Marcar como latido regular",
    "Marcar como pausa maior": "Marcar como pausa mayor",
    "Nenhum trecho de movimento marcado nesta gravação.": "Ningún tramo de movimiento marcado en esta grabación.",
    "Nenhuma gravação carregada.": "Ninguna grabación cargada.",
    "Nenhuma piscada ou movimento dos olhos encontrado.": "No se encontró ningún parpadeo ni movimiento de los ojos.",
    "Novo trecho aqui": "Nuevo tramo aquí",
    "Não foi possível salvar: {0}": "No se pudo guardar: {0}",
    "Os músculos ativos ({0}) não combinam com o movimento escolhido ({1}); esperado: {2}.": "Los músculos activos ({0}) no coinciden con el movimiento elegido ({1}); esperado: {2}.",
    "Pinça": "Pinza",
    "Pronação": "Pronación",
    "Pronação (palma para baixo)": "Pronación (palma hacia abajo)",
    "Protocolo: fim": "Protocolo: fin",
    "Protocolo: início": "Protocolo: inicio",
    "Refazer": "Rehacer",
    "Remover batida": "Eliminar latido",
    "Remover faixa": "Eliminar pista",
    "Repetir": "Repetir",
    "Replay": "Reproducción",
    "Supinação": "Supinación",
    "Supinação (palma para cima)": "Supinación (palma hacia arriba)",
    "Toca ou pausa o replay (barra de espaço).": "Reproduce o pausa la reproducción (barra espaciadora).",
    "Todas as batidas foram regulares.": "Todos los latidos fueron regulares.",
    "Trocar o movimento": "Cambiar el movimiento",
    "Velocidade do replay (não muda a gravação).": "Velocidad de la reproducción (no cambia la grabación).",
    "Volta para o começo da gravação.": "Vuelve al comienzo de la grabación.",
    "adiantada": "adelantado",
    "aguardando a primeira batida": "esperando el primer latido",
    "baixo": "abajo",
    "batida adiantada": "latido adelantado",
    "batida regular": "latido regular",
    "bpm em média: —": "bpm de media: —",
    "cima": "arriba",
    "direita": "derecha",
    "esquerda": "izquierda",
    "faixa {0}": "pista {0}",
    "nenhuma adiantada": "ninguno adelantado",
    "nenhuma batida": "ningún latido",
    "nenhuma pausa": "ninguna pausa",
    "olhando para a direita": "mirando a la derecha",
    "olhando para a esquerda": "mirando a la izquierda",
    "olhando para baixo": "mirando hacia abajo",
    "olhando para cima": "mirando hacia arriba",
    "olhando para frente": "mirando al frente",
    "pausa": "pausa",
    "pausa maior": "pausa mayor",
    "piscadas: {0} · para os lados: {1} · para cima ou baixo: {2}": "parpadeos: {0} · a los lados: {1} · arriba o abajo: {2}",
    "piscando": "parpadeando",
    "regular": "regular",
    "{0} adiantada": "{0} adelantado",
    "{0} adiantadas": "{0} adelantados",
    "{0} batida": "{0} latido",
    "{0} batidas": "{0} latidos",
    "{0} bpm em média": "{0} bpm de media",
    "{0} evento": "{0} evento",
    "{0} ficou olhando para a direita": "{0} se quedó mirando a la derecha",
    "{0} ficou olhando para a esquerda": "{0} se quedó mirando a la izquierda",
    "{0} ficou olhando para baixo": "{0} se quedó mirando hacia abajo",
    "{0} ficou olhando para cima": "{0} se quedó mirando hacia arriba",
    "{0} ficou olhando para frente": "{0} se quedó mirando al frente",
    "{0} moveu os olhos": "{0} movió los ojos",
    "{0} olhou para a direita": "{0} miró a la derecha",
    "{0} olhou para a esquerda": "{0} miró a la izquierda",
    "{0} olhou para baixo": "{0} miró hacia abajo",
    "{0} olhou para cima": "{0} miró hacia arriba",
    "{0} pausa": "{0} pausa",
    "{0} pausas": "{0} pausas",
    "{0} piscou": "{0} parpadeó",
    "{0} por {1} s": "{0} durante {1} s",
    "⏮ Início": "⏮ Inicio",
    "⏸ Pausar": "⏸ Pausar",
    "▶ Tocar": "▶ Reproducir",
}
