# -*- coding: utf-8 -*-
"""Lote "replay_p6p7": traduções pt -> fr. Preencha os valores vazios."""
TRAD = {
    "(corrigida à mão)": "(corrigé à la main)",
    "(corrigido à mão)": "(corrigé à la main)",
    "A animação SIMULA o que foi gravado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "L'animation SIMULE ce qui a été enregistré ; ce n'est pas une vidéo de la personne. Ce n'est ni un compte rendu médical ni un diagnostic.",
    "A definir": "À définir",
    "Abrir a mão": "Ouvrir la main",
    "Abrir mão": "Main ouverte",
    "Adicionar batida aqui": "Ajouter un battement ici",
    "Adicionar faixa": "Ajouter une piste",
    "Apagar": "Effacer",
    "Arraste para ir a um instante da gravação.": "Faites glisser pour aller à un instant de l'enregistrement.",
    "Desfazer": "Annuler",
    "Dividir aqui": "Scinder ici",
    "Ext. cotovelo": "Ext. coude",
    "Ext. ombro": "Ext. épaule",
    "Ext. punho": "Ext. poignet",
    "Extensão do cotovelo": "Extension du coude",
    "Extensão do ombro": "Extension de l'épaule",
    "Extensão do punho": "Extension du poignet",
    "Faixa {0}": "Piste {0}",
    "Fechar a mão": "Fermer la main",
    "Fechar mão": "Main fermée",
    "Flex. cotovelo": "Flex. coude",
    "Flex. ombro": "Flex. épaule",
    "Flex. punho": "Flex. poignet",
    "Flexão do cotovelo": "Flexion du coude",
    "Flexão do ombro": "Flexion de l'épaule",
    "Flexão do punho": "Flexion du poignet",
    "Grava as marcações ao lado da gravação.": "Enregistre les marquages à côté de l'enregistrement.",
    "Há marcações não salvas. Salvar antes de fechar?": "Il y a des marquages non sauvegardés. Sauvegarder avant de fermer ?",
    "Isto não é laudo nem diagnóstico.": "Ceci n'est ni un compte rendu médical ni un diagnostic.",
    "Marcar como batida adiantada": "Marquer comme battement en avance",
    "Marcar como batida regular": "Marquer comme battement régulier",
    "Marcar como pausa maior": "Marquer comme pause plus longue",
    "Nenhum trecho de movimento marcado nesta gravação.": "Aucun segment de mouvement marqué dans cet enregistrement.",
    "Nenhuma gravação carregada.": "Aucun enregistrement chargé.",
    "Nenhuma piscada ou movimento dos olhos encontrado.": "Aucun clignement ni mouvement des yeux trouvé.",
    "Novo trecho aqui": "Nouveau segment ici",
    "Não foi possível salvar: {0}": "Impossible de sauvegarder : {0}",
    "Os músculos ativos ({0}) não combinam com o movimento escolhido ({1}); esperado: {2}.": "Les muscles actifs ({0}) ne correspondent pas au mouvement choisi ({1}) ; attendu : {2}.",
    "Pinça": "Pince",
    "Pronação": "Pronation",
    "Pronação (palma para baixo)": "Pronation (paume vers le bas)",
    "Protocolo: fim": "Protocole : fin",
    "Protocolo: início": "Protocole : début",
    "Refazer": "Rétablir",
    "Remover batida": "Supprimer le battement",
    "Remover faixa": "Supprimer la piste",
    "Repetir": "Répéter",
    "Replay": "Replay",
    "Supinação": "Supination",
    "Supinação (palma para cima)": "Supination (paume vers le haut)",
    "Toca ou pausa o replay (barra de espaço).": "Lance ou met en pause le replay (barre d'espace).",
    "Todas as batidas foram regulares.": "Tous les battements ont été réguliers.",
    "Trocar o movimento": "Changer le mouvement",
    "Velocidade do replay (não muda a gravação).": "Vitesse du replay (ne modifie pas l'enregistrement).",
    "Volta para o começo da gravação.": "Revient au début de l'enregistrement.",
    "adiantada": "en avance",
    "aguardando a primeira batida": "en attente du premier battement",
    "baixo": "bas",
    "batida adiantada": "battement en avance",
    "batida regular": "battement régulier",
    "bpm em média: —": "bpm en moyenne : —",
    "cima": "haut",
    "direita": "droite",
    "esquerda": "gauche",
    "faixa {0}": "piste {0}",
    "nenhuma adiantada": "aucun en avance",
    "nenhuma batida": "aucun battement",
    "nenhuma pausa": "aucune pause",
    "olhando para a direita": "regarde à droite",
    "olhando para a esquerda": "regarde à gauche",
    "olhando para baixo": "regarde en bas",
    "olhando para cima": "regarde en haut",
    "olhando para frente": "regarde devant",
    "pausa": "pause",
    "pausa maior": "pause plus longue",
    "piscadas: {0} · para os lados: {1} · para cima ou baixo: {2}": "clignements : {0} · sur les côtés : {1} · en haut ou en bas : {2}",
    "piscando": "cligne des yeux",
    "regular": "régulier",
    "{0} adiantada": "{0} en avance",
    "{0} adiantadas": "{0} en avance",
    "{0} batida": "{0} battement",
    "{0} batidas": "{0} battements",
    "{0} bpm em média": "{0} bpm en moyenne",
    "{0} evento": "{0} événement",
    "{0} ficou olhando para a direita": "{0} a gardé le regard à droite",
    "{0} ficou olhando para a esquerda": "{0} a gardé le regard à gauche",
    "{0} ficou olhando para baixo": "{0} a gardé le regard en bas",
    "{0} ficou olhando para cima": "{0} a gardé le regard en haut",
    "{0} ficou olhando para frente": "{0} a gardé le regard devant",
    "{0} moveu os olhos": "{0} a bougé les yeux",
    "{0} olhou para a direita": "{0} a regardé à droite",
    "{0} olhou para a esquerda": "{0} a regardé à gauche",
    "{0} olhou para baixo": "{0} a regardé en bas",
    "{0} olhou para cima": "{0} a regardé en haut",
    "{0} pausa": "{0} pause",
    "{0} pausas": "{0} pauses",
    "{0} piscou": "{0} a cligné des yeux",
    "{0} por {1} s": "{0} pendant {1} s",
    "⏮ Início": "⏮ Début",
    "⏸ Pausar": "⏸ Pause",
    "▶ Tocar": "▶ Lecture",
}
