# -*- coding: utf-8 -*-
"""Lote "replay_p6p7": traduções pt -> it. Preencha os valores vazios."""
TRAD = {
    "(corrigida à mão)": "(corretto a mano)",
    "(corrigido à mão)": "(corretto a mano)",
    "A animação SIMULA o que foi gravado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "L'animazione SIMULA ciò che è stato registrato; non è un video della persona. Non è un referto né una diagnosi.",
    "A definir": "Da definire",
    "Abrir a mão": "Aprire la mano",
    "Abrir mão": "Apertura mano",
    "Adicionar batida aqui": "Aggiungi battito qui",
    "Adicionar faixa": "Aggiungi traccia",
    "Apagar": "Elimina",
    "Arraste para ir a um instante da gravação.": "Trascina per andare a un istante della registrazione.",
    "Desfazer": "Annulla",
    "Dividir aqui": "Dividi qui",
    "Ext. cotovelo": "Est. gomito",
    "Ext. ombro": "Est. spalla",
    "Ext. punho": "Est. polso",
    "Extensão do cotovelo": "Estensione del gomito",
    "Extensão do ombro": "Estensione della spalla",
    "Extensão do punho": "Estensione del polso",
    "Faixa {0}": "Traccia {0}",
    "Fechar a mão": "Chiudere la mano",
    "Fechar mão": "Chiusura mano",
    "Flex. cotovelo": "Fless. gomito",
    "Flex. ombro": "Fless. spalla",
    "Flex. punho": "Fless. polso",
    "Flexão do cotovelo": "Flessione del gomito",
    "Flexão do ombro": "Flessione della spalla",
    "Flexão do punho": "Flessione del polso",
    "Grava as marcações ao lado da gravação.": "Salva le marcature accanto alla registrazione.",
    "Há marcações não salvas. Salvar antes de fechar?": "Ci sono marcature non salvate. Salvare prima di chiudere?",
    "Isto não é laudo nem diagnóstico.": "Questo non è un referto né una diagnosi.",
    "Marcar como batida adiantada": "Segna come battito anticipato",
    "Marcar como batida regular": "Segna come battito regolare",
    "Marcar como pausa maior": "Segna come pausa più lunga",
    "Nenhum trecho de movimento marcado nesta gravação.": "Nessun tratto di movimento contrassegnato in questa registrazione.",
    "Nenhuma gravação carregada.": "Nessuna registrazione caricata.",
    "Nenhuma piscada ou movimento dos olhos encontrado.": "Nessun ammiccamento o movimento degli occhi trovato.",
    "Novo trecho aqui": "Nuovo tratto qui",
    "Não foi possível salvar: {0}": "Impossibile salvare: {0}",
    "Os músculos ativos ({0}) não combinam com o movimento escolhido ({1}); esperado: {2}.": "I muscoli attivi ({0}) non corrispondono al movimento scelto ({1}); atteso: {2}.",
    "Pinça": "Pinza",
    "Pronação": "Pronazione",
    "Pronação (palma para baixo)": "Pronazione (palmo in giù)",
    "Protocolo: fim": "Protocollo: fine",
    "Protocolo: início": "Protocollo: inizio",
    "Refazer": "Ripeti",
    "Remover batida": "Rimuovi battito",
    "Remover faixa": "Rimuovi traccia",
    "Repetir": "In loop",
    "Replay": "Replay",
    "Supinação": "Supinazione",
    "Supinação (palma para cima)": "Supinazione (palmo in su)",
    "Toca ou pausa o replay (barra de espaço).": "Avvia o mette in pausa il replay (barra spaziatrice).",
    "Todas as batidas foram regulares.": "Tutti i battiti sono stati regolari.",
    "Trocar o movimento": "Cambia movimento",
    "Velocidade do replay (não muda a gravação).": "Velocità del replay (non modifica la registrazione).",
    "Volta para o começo da gravação.": "Torna all'inizio della registrazione.",
    "adiantada": "anticipato",
    "aguardando a primeira batida": "in attesa del primo battito",
    "baixo": "giù",
    "batida adiantada": "battito anticipato",
    "batida regular": "battito regolare",
    "bpm em média: —": "bpm in media: —",
    "cima": "su",
    "direita": "destra",
    "esquerda": "sinistra",
    "faixa {0}": "traccia {0}",
    "nenhuma adiantada": "nessuno anticipato",
    "nenhuma batida": "nessun battito",
    "nenhuma pausa": "nessuna pausa",
    "olhando para a direita": "guarda a destra",
    "olhando para a esquerda": "guarda a sinistra",
    "olhando para baixo": "guarda in basso",
    "olhando para cima": "guarda in alto",
    "olhando para frente": "guarda avanti",
    "pausa": "pausa",
    "pausa maior": "pausa più lunga",
    "piscadas: {0} · para os lados: {1} · para cima ou baixo: {2}": "ammiccamenti: {0} · di lato: {1} · in alto o in basso: {2}",
    "piscando": "sbatte le palpebre",
    "regular": "regolare",
    "{0} adiantada": "{0} anticipato",
    "{0} adiantadas": "{0} anticipati",
    "{0} batida": "{0} battito",
    "{0} batidas": "{0} battiti",
    "{0} bpm em média": "{0} bpm in media",
    "{0} evento": "{0} evento",
    "{0} ficou olhando para a direita": "{0} ha tenuto lo sguardo a destra",
    "{0} ficou olhando para a esquerda": "{0} ha tenuto lo sguardo a sinistra",
    "{0} ficou olhando para baixo": "{0} ha tenuto lo sguardo in basso",
    "{0} ficou olhando para cima": "{0} ha tenuto lo sguardo in alto",
    "{0} ficou olhando para frente": "{0} ha tenuto lo sguardo avanti",
    "{0} moveu os olhos": "{0} ha mosso gli occhi",
    "{0} olhou para a direita": "{0} ha guardato a destra",
    "{0} olhou para a esquerda": "{0} ha guardato a sinistra",
    "{0} olhou para baixo": "{0} ha guardato in basso",
    "{0} olhou para cima": "{0} ha guardato in alto",
    "{0} pausa": "{0} pausa",
    "{0} pausas": "{0} pause",
    "{0} piscou": "{0} ha sbattuto le palpebre",
    "{0} por {1} s": "{0} per {1} s",
    "⏮ Início": "⏮ Inizio",
    "⏸ Pausar": "⏸ Pausa",
    "▶ Tocar": "▶ Riproduci",
}
