# -*- coding: utf-8 -*-
"""Lote "replay_p6p7": traduções pt -> ja. Preencha os valores vazios."""
TRAD = {
    "(corrigida à mão)": "（手動で修正）",
    "(corrigido à mão)": "（手動で修正）",
    "A animação SIMULA o que foi gravado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "このアニメーションは記録された内容を再現（シミュレーション）したもので、本人の映像ではありません。診断書でも診断でもありません。",
    "A definir": "未設定",
    "Abrir a mão": "手を開く",
    "Abrir mão": "手を開く",
    "Adicionar batida aqui": "ここに拍を追加",
    "Adicionar faixa": "トラックを追加",
    "Apagar": "削除",
    "Arraste para ir a um instante da gravação.": "ドラッグして記録内の時点へ移動します。",
    "Desfazer": "元に戻す",
    "Dividir aqui": "ここで分割",
    "Ext. cotovelo": "肘伸展",
    "Ext. ombro": "肩伸展",
    "Ext. punho": "手首伸展",
    "Extensão do cotovelo": "肘の伸展",
    "Extensão do ombro": "肩の伸展",
    "Extensão do punho": "手関節の伸展",
    "Faixa {0}": "トラック {0}",
    "Fechar a mão": "手を閉じる",
    "Fechar mão": "手を閉じる",
    "Flex. cotovelo": "肘屈曲",
    "Flex. ombro": "肩屈曲",
    "Flex. punho": "手首屈曲",
    "Flexão do cotovelo": "肘の屈曲",
    "Flexão do ombro": "肩の屈曲",
    "Flexão do punho": "手関節の屈曲",
    "Grava as marcações ao lado da gravação.": "マークを記録と同じ場所に保存します。",
    "Há marcações não salvas. Salvar antes de fechar?": "保存していないマークがあります。閉じる前に保存しますか？",
    "Isto não é laudo nem diagnóstico.": "これは診断書でも診断でもありません。",
    "Marcar como batida adiantada": "早い拍として印を付ける",
    "Marcar como batida regular": "規則的な拍として印を付ける",
    "Marcar como pausa maior": "長めの休止として印を付ける",
    "Nenhum trecho de movimento marcado nesta gravação.": "この記録には動作の区間が1つもマークされていません。",
    "Nenhuma gravação carregada.": "記録が読み込まれていません。",
    "Nenhuma piscada ou movimento dos olhos encontrado.": "まばたきも目の動きも見つかりませんでした。",
    "Novo trecho aqui": "ここに新しい区間",
    "Não foi possível salvar: {0}": "保存できませんでした：{0}",
    "Os músculos ativos ({0}) não combinam com o movimento escolhido ({1}); esperado: {2}.": "活動している筋（{0}）が選んだ動作（{1}）と合いません。想定：{2}。",
    "Pinça": "つまみ",
    "Pronação": "回内",
    "Pronação (palma para baixo)": "回内（手のひらを下に）",
    "Protocolo: fim": "プロトコル：終了",
    "Protocolo: início": "プロトコル：開始",
    "Refazer": "やり直す",
    "Remover batida": "拍を削除",
    "Remover faixa": "トラックを削除",
    "Repetir": "リピート",
    "Replay": "リプレイ",
    "Supinação": "回外",
    "Supinação (palma para cima)": "回外（手のひらを上に）",
    "Toca ou pausa o replay (barra de espaço).": "リプレイを再生または一時停止します（スペースキー）。",
    "Todas as batidas foram regulares.": "すべての拍が規則的でした。",
    "Trocar o movimento": "動作を変更",
    "Velocidade do replay (não muda a gravação).": "リプレイの速度（記録は変わりません）。",
    "Volta para o começo da gravação.": "記録の先頭に戻ります。",
    "adiantada": "早い",
    "aguardando a primeira batida": "最初の拍を待っています",
    "baixo": "下",
    "batida adiantada": "早い拍",
    "batida regular": "規則的な拍",
    "bpm em média: —": "平均 bpm：—",
    "cima": "上",
    "direita": "右",
    "esquerda": "左",
    "faixa {0}": "トラック {0}",
    "nenhuma adiantada": "早い拍なし",
    "nenhuma batida": "拍なし",
    "nenhuma pausa": "休止なし",
    "olhando para a direita": "右を見ている",
    "olhando para a esquerda": "左を見ている",
    "olhando para baixo": "下を見ている",
    "olhando para cima": "上を見ている",
    "olhando para frente": "正面を見ている",
    "pausa": "休止",
    "pausa maior": "長めの休止",
    "piscadas: {0} · para os lados: {1} · para cima ou baixo: {2}": "まばたき：{0} · 左右：{1} · 上下：{2}",
    "piscando": "まばたき中",
    "regular": "規則的",
    "{0} adiantada": "早い拍 {0} 回",
    "{0} adiantadas": "早い拍 {0} 回",
    "{0} batida": "{0} 拍",
    "{0} batidas": "{0} 拍",
    "{0} bpm em média": "平均 {0} bpm",
    "{0} evento": "{0} イベント",
    "{0} ficou olhando para a direita": "{0} 右を見続けた",
    "{0} ficou olhando para a esquerda": "{0} 左を見続けた",
    "{0} ficou olhando para baixo": "{0} 下を見続けた",
    "{0} ficou olhando para cima": "{0} 上を見続けた",
    "{0} ficou olhando para frente": "{0} 正面を見続けた",
    "{0} moveu os olhos": "{0} 目を動かした",
    "{0} olhou para a direita": "{0} 右を見た",
    "{0} olhou para a esquerda": "{0} 左を見た",
    "{0} olhou para baixo": "{0} 下を見た",
    "{0} olhou para cima": "{0} 上を見た",
    "{0} pausa": "休止 {0} 回",
    "{0} pausas": "休止 {0} 回",
    "{0} piscou": "{0} まばたき",
    "{0} por {1} s": "{0}（{1} 秒間）",
    "⏮ Início": "⏮ 先頭",
    "⏸ Pausar": "⏸ 一時停止",
    "▶ Tocar": "▶ 再生",
}
