# -*- coding: utf-8 -*-
"""Lote "replay_p6p7": traduções pt -> ru. Preencha os valores vazios."""
TRAD = {
    "(corrigida à mão)": "(исправлено вручную)",
    "(corrigido à mão)": "(исправлено вручную)",
    "A animação SIMULA o que foi gravado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "Анимация ИМИТИРУЕТ записанное; это не видео человека. Это не заключение и не диагноз.",
    "A definir": "Не задано",
    "Abrir a mão": "Раскрыть кисть",
    "Abrir mão": "Раскрыть кисть",
    "Adicionar batida aqui": "Добавить удар здесь",
    "Adicionar faixa": "Добавить дорожку",
    "Apagar": "Удалить",
    "Arraste para ir a um instante da gravação.": "Перетащите, чтобы перейти к нужному моменту записи.",
    "Desfazer": "Отменить",
    "Dividir aqui": "Разделить здесь",
    "Ext. cotovelo": "Разг. предпл.",
    "Ext. ombro": "Разг. плеча",
    "Ext. punho": "Разг. кисти",
    "Extensão do cotovelo": "Разгибание предплечья",
    "Extensão do ombro": "Разгибание плеча",
    "Extensão do punho": "Разгибание кисти",
    "Faixa {0}": "Дорожка {0}",
    "Fechar a mão": "Сжать кисть",
    "Fechar mão": "Сжать кисть",
    "Flex. cotovelo": "Сгиб. предпл.",
    "Flex. ombro": "Сгиб. плеча",
    "Flex. punho": "Сгиб. кисти",
    "Flexão do cotovelo": "Сгибание предплечья",
    "Flexão do ombro": "Сгибание плеча",
    "Flexão do punho": "Сгибание кисти",
    "Grava as marcações ao lado da gravação.": "Сохраняет отметки рядом с записью.",
    "Há marcações não salvas. Salvar antes de fechar?": "Есть несохранённые отметки. Сохранить перед закрытием?",
    "Isto não é laudo nem diagnóstico.": "Это не заключение и не диагноз.",
    "Marcar como batida adiantada": "Отметить как ранний удар",
    "Marcar como batida regular": "Отметить как обычный удар",
    "Marcar como pausa maior": "Отметить как длинную паузу",
    "Nenhum trecho de movimento marcado nesta gravação.": "В этой записи не отмечено ни одного участка движения.",
    "Nenhuma gravação carregada.": "Запись не загружена.",
    "Nenhuma piscada ou movimento dos olhos encontrado.": "Моргания и движения глаз не найдены.",
    "Novo trecho aqui": "Новый участок здесь",
    "Não foi possível salvar: {0}": "Не удалось сохранить: {0}",
    "Os músculos ativos ({0}) não combinam com o movimento escolhido ({1}); esperado: {2}.": "Активные мышцы ({0}) не соответствуют выбранному движению ({1}); ожидалось: {2}.",
    "Pinça": "Щипок",
    "Pronação": "Пронация",
    "Pronação (palma para baixo)": "Пронация (ладонью вниз)",
    "Protocolo: fim": "Протокол: конец",
    "Protocolo: início": "Протокол: начало",
    "Refazer": "Вернуть",
    "Remover batida": "Удалить удар",
    "Remover faixa": "Удалить дорожку",
    "Repetir": "Повтор",
    "Replay": "Воспроизведение",
    "Supinação": "Супинация",
    "Supinação (palma para cima)": "Супинация (ладонью вверх)",
    "Toca ou pausa o replay (barra de espaço).": "Запускает или приостанавливает воспроизведение (пробел).",
    "Todas as batidas foram regulares.": "Все удары были обычными.",
    "Trocar o movimento": "Сменить движение",
    "Velocidade do replay (não muda a gravação).": "Скорость воспроизведения (запись не меняется).",
    "Volta para o começo da gravação.": "Возвращает к началу записи.",
    "adiantada": "ранний",
    "aguardando a primeira batida": "ожидание первого удара",
    "baixo": "вниз",
    "batida adiantada": "ранний удар",
    "batida regular": "обычный удар",
    "bpm em média: —": "средний bpm: —",
    "cima": "вверх",
    "direita": "вправо",
    "esquerda": "влево",
    "faixa {0}": "дорожка {0}",
    "nenhuma adiantada": "ранних нет",
    "nenhuma batida": "ударов нет",
    "nenhuma pausa": "пауз нет",
    "olhando para a direita": "смотрит вправо",
    "olhando para a esquerda": "смотрит влево",
    "olhando para baixo": "смотрит вниз",
    "olhando para cima": "смотрит вверх",
    "olhando para frente": "смотрит прямо",
    "pausa": "пауза",
    "pausa maior": "длинная пауза",
    "piscadas: {0} · para os lados: {1} · para cima ou baixo: {2}": "морганий: {0} · в стороны: {1} · вверх или вниз: {2}",
    "piscando": "моргает",
    "regular": "обычный",
    "{0} adiantada": "{0} ранний",
    "{0} adiantadas": "ранних: {0}",
    "{0} batida": "{0} удар",
    "{0} batidas": "ударов: {0}",
    "{0} bpm em média": "в среднем {0} bpm",
    "{0} evento": "{0} событие",
    "{0} ficou olhando para a direita": "{0} смотрит вправо",
    "{0} ficou olhando para a esquerda": "{0} смотрит влево",
    "{0} ficou olhando para baixo": "{0} смотрит вниз",
    "{0} ficou olhando para cima": "{0} смотрит вверх",
    "{0} ficou olhando para frente": "{0} смотрит прямо",
    "{0} moveu os olhos": "{0} движение глаз",
    "{0} olhou para a direita": "{0} взгляд вправо",
    "{0} olhou para a esquerda": "{0} взгляд влево",
    "{0} olhou para baixo": "{0} взгляд вниз",
    "{0} olhou para cima": "{0} взгляд вверх",
    "{0} pausa": "{0} пауза",
    "{0} pausas": "пауз: {0}",
    "{0} piscou": "{0} моргание",
    "{0} por {1} s": "{0} в течение {1} с",
    "⏮ Início": "⏮ Начало",
    "⏸ Pausar": "⏸ Пауза",
    "▶ Tocar": "▶ Пуск",
}
