# -*- coding: utf-8 -*-
"""Lote "replay_p6p7": traduções pt -> zh. Preencha os valores vazios."""
TRAD = {
    "(corrigida à mão)": "（手动修正）",
    "(corrigido à mão)": "（手动修正）",
    "A animação SIMULA o que foi gravado; não é vídeo da pessoa. Não é laudo nem diagnóstico.": "动画只是模拟所记录的内容，并非本人的视频。不是诊断报告，也不是诊断。",
    "A definir": "待定",
    "Abrir a mão": "张开手",
    "Abrir mão": "张手",
    "Adicionar batida aqui": "在此添加心跳",
    "Adicionar faixa": "添加轨道",
    "Apagar": "删除",
    "Arraste para ir a um instante da gravação.": "拖动以跳到记录中的某一时刻。",
    "Desfazer": "撤销",
    "Dividir aqui": "在此拆分",
    "Ext. cotovelo": "伸肘",
    "Ext. ombro": "伸肩",
    "Ext. punho": "伸腕",
    "Extensão do cotovelo": "肘关节伸展",
    "Extensão do ombro": "肩关节伸展",
    "Extensão do punho": "腕关节伸展",
    "Faixa {0}": "轨道 {0}",
    "Fechar a mão": "握紧手",
    "Fechar mão": "握拳",
    "Flex. cotovelo": "屈肘",
    "Flex. ombro": "屈肩",
    "Flex. punho": "屈腕",
    "Flexão do cotovelo": "肘关节屈曲",
    "Flexão do ombro": "肩关节屈曲",
    "Flexão do punho": "腕关节屈曲",
    "Grava as marcações ao lado da gravação.": "将标记保存在记录旁边。",
    "Há marcações não salvas. Salvar antes de fechar?": "有未保存的标记。关闭前先保存吗？",
    "Isto não é laudo nem diagnóstico.": "这不是诊断报告，也不是诊断。",
    "Marcar como batida adiantada": "标记为提前心跳",
    "Marcar como batida regular": "标记为规律心跳",
    "Marcar como pausa maior": "标记为较长停顿",
    "Nenhum trecho de movimento marcado nesta gravação.": "此记录中未标记任何动作片段。",
    "Nenhuma gravação carregada.": "未加载任何记录。",
    "Nenhuma piscada ou movimento dos olhos encontrado.": "未发现眨眼或眼球运动。",
    "Novo trecho aqui": "在此新建片段",
    "Não foi possível salvar: {0}": "无法保存：{0}",
    "Os músculos ativos ({0}) não combinam com o movimento escolhido ({1}); esperado: {2}.": "活动的肌肉（{0}）与所选动作（{1}）不匹配；预期：{2}。",
    "Pinça": "捏取",
    "Pronação": "旋前",
    "Pronação (palma para baixo)": "旋前（掌心向下）",
    "Protocolo: fim": "协议：结束",
    "Protocolo: início": "协议：开始",
    "Refazer": "重做",
    "Remover batida": "移除心跳",
    "Remover faixa": "移除轨道",
    "Repetir": "循环",
    "Replay": "回放",
    "Supinação": "旋后",
    "Supinação (palma para cima)": "旋后（掌心向上）",
    "Toca ou pausa o replay (barra de espaço).": "播放或暂停回放（空格键）。",
    "Todas as batidas foram regulares.": "所有心跳均规律。",
    "Trocar o movimento": "更换动作",
    "Velocidade do replay (não muda a gravação).": "回放速度（不改变记录）。",
    "Volta para o começo da gravação.": "回到记录的开头。",
    "adiantada": "提前",
    "aguardando a primeira batida": "等待第一次心跳",
    "baixo": "下",
    "batida adiantada": "提前心跳",
    "batida regular": "规律心跳",
    "bpm em média: —": "平均 bpm：—",
    "cima": "上",
    "direita": "右",
    "esquerda": "左",
    "faixa {0}": "轨道 {0}",
    "nenhuma adiantada": "无提前",
    "nenhuma batida": "无心跳",
    "nenhuma pausa": "无停顿",
    "olhando para a direita": "看向右边",
    "olhando para a esquerda": "看向左边",
    "olhando para baixo": "看向下方",
    "olhando para cima": "看向上方",
    "olhando para frente": "看向正前方",
    "pausa": "停顿",
    "pausa maior": "较长停顿",
    "piscadas: {0} · para os lados: {1} · para cima ou baixo: {2}": "眨眼：{0} · 左右：{1} · 上下：{2}",
    "piscando": "正在眨眼",
    "regular": "规律",
    "{0} adiantada": "{0} 次提前",
    "{0} adiantadas": "{0} 次提前",
    "{0} batida": "{0} 次心跳",
    "{0} batidas": "{0} 次心跳",
    "{0} bpm em média": "平均 {0} bpm",
    "{0} evento": "{0} 事件",
    "{0} ficou olhando para a direita": "{0} 一直看着右边",
    "{0} ficou olhando para a esquerda": "{0} 一直看着左边",
    "{0} ficou olhando para baixo": "{0} 一直看着下方",
    "{0} ficou olhando para cima": "{0} 一直看着上方",
    "{0} ficou olhando para frente": "{0} 一直看着正前方",
    "{0} moveu os olhos": "{0} 眼睛动了",
    "{0} olhou para a direita": "{0} 向右看",
    "{0} olhou para a esquerda": "{0} 向左看",
    "{0} olhou para baixo": "{0} 向下看",
    "{0} olhou para cima": "{0} 向上看",
    "{0} pausa": "{0} 次停顿",
    "{0} pausas": "{0} 次停顿",
    "{0} piscou": "{0} 眨眼",
    "{0} por {1} s": "{0}，持续 {1} 秒",
    "⏮ Início": "⏮ 开头",
    "⏸ Pausar": "⏸ 暂停",
    "▶ Tocar": "▶ 播放",
}
