# -*- coding: utf-8 -*-
"""Lote "p3_atlas": traduções pt -> de."""
TRAD = {
    "Bíceps": "Bizeps",
    "Clique em 'Adicionar eletrodo' e clique no corpo: o eletrodo cola no\nponto SENIAM mais próximo (ventre do músculo) ou fica onde você clicou.\nARRASTE o eletrodo: o calor acompanha e mostra a intensidade medida ali.\nRoda do mouse amplia; botão direito arrasta a vista ampliada.\nDuplo-clique renomeia · Delete remove o selecionado.": "Klicken Sie auf „Elektrode hinzufügen“ und dann auf den Körper: die Elektrode rastet am\nnächsten SENIAM-Punkt (Muskelbauch) ein oder bleibt dort, wo Sie geklickt haben.\nZIEHEN Sie die Elektrode: die Wärme folgt ihr und zeigt die dort gemessene Intensität.\nMausrad zoomt; rechte Taste verschiebt die vergrößerte Ansicht.\nDoppelklick benennt um · Entf entfernt die ausgewählte.",
    "Delt. ant.": "Vord. Delt.",
    "Delt. médio": "Mittl. Delt.",
    "Delt. post.": "Hint. Delt.",
    "ECM": "SCM",
    "ECR": "ECR",
    "Eretor esp.": "Rückenstr.",
    "Ext. dedos": "Fingerstr.",
    "FCR": "FCR",
    "Fibular": "Peroneus",
    "Flex. dedos": "Fingerbeuger",
    "Frontal": "Frontalis",
    "Gastroc. med.": "Med. Gastroc.",
    "Glúteo máx.": "Glut. max.",
    "Glúteo méd.": "Glut. med.",
    "Isquiotib.": "Ischiocrurale",
    "Lado": "Seite",
    "Lateral": "Lateral",
    "Latíssimo": "Latissimus",
    "Masseter": "Masseter",
    "Orbicular": "Orbicularis",
    "Peitoral": "Pectoralis",
    "Reto abd.": "Rectus abd.",
    "Reto fem.": "Rectus fem.",
    "Temporal": "Temporalis",
    "Tibial ant.": "Tib. ant.",
    "Trap. sup.": "Ob. Trapez",
    "Tríceps": "Trizeps",
    "Vasto lat.": "Vastus lat.",
    "Vasto med.": "Vastus med.",
    "Vista Lateral (perfil esquerdo)": "Seitenansicht (linkes Profil)",
    "Zigomático": "Zygomaticus",
}
