# -*- coding: utf-8 -*-
"""Lote "p3_atlas": traduções pt -> en."""
TRAD = {
    "Bíceps": "Biceps",
    "Clique em 'Adicionar eletrodo' e clique no corpo: o eletrodo cola no\nponto SENIAM mais próximo (ventre do músculo) ou fica onde você clicou.\nARRASTE o eletrodo: o calor acompanha e mostra a intensidade medida ali.\nRoda do mouse amplia; botão direito arrasta a vista ampliada.\nDuplo-clique renomeia · Delete remove o selecionado.": "Click 'Add electrode' and then click on the body: the electrode snaps to the\nnearest SENIAM point (muscle belly) or stays where you clicked.\nDRAG the electrode: the heat follows it and shows the intensity measured there.\nMouse wheel zooms; right button drags the zoomed view.\nDouble-click renames · Delete removes the selected one.",
    "Delt. ant.": "Ant. delt.",
    "Delt. médio": "Mid. delt.",
    "Delt. post.": "Post. delt.",
    "ECM": "SCM",
    "ECR": "ECR",
    "Eretor esp.": "Erector sp.",
    "Ext. dedos": "Finger ext.",
    "FCR": "FCR",
    "Fibular": "Peroneus",
    "Flex. dedos": "Finger flex.",
    "Frontal": "Frontalis",
    "Gastroc. med.": "Med. gastroc.",
    "Glúteo máx.": "Glut. max.",
    "Glúteo méd.": "Glut. med.",
    "Isquiotib.": "Hamstrings",
    "Lado": "Side",
    "Lateral": "Lateral",
    "Latíssimo": "Latissimus",
    "Masseter": "Masseter",
    "Orbicular": "Orbicularis",
    "Peitoral": "Pectoralis",
    "Reto abd.": "Rectus abd.",
    "Reto fem.": "Rectus fem.",
    "Temporal": "Temporalis",
    "Tibial ant.": "Tib. ant.",
    "Trap. sup.": "Upper trap.",
    "Tríceps": "Triceps",
    "Vasto lat.": "Vastus lat.",
    "Vasto med.": "Vastus med.",
    "Vista Lateral (perfil esquerdo)": "Side View (left profile)",
    "Zigomático": "Zygomaticus",
}
