# -*- coding: utf-8 -*-
"""Lote "p3_atlas": traduções pt -> es."""
TRAD = {
    "Bíceps": "Bíceps",
    "Clique em 'Adicionar eletrodo' e clique no corpo: o eletrodo cola no\nponto SENIAM mais próximo (ventre do músculo) ou fica onde você clicou.\nARRASTE o eletrodo: o calor acompanha e mostra a intensidade medida ali.\nRoda do mouse amplia; botão direito arrasta a vista ampliada.\nDuplo-clique renomeia · Delete remove o selecionado.": "Haga clic en 'Añadir electrodo' y luego en el cuerpo: el electrodo se pega al\npunto SENIAM más cercano (vientre del músculo) o queda donde hizo clic.\nARRASTRE el electrodo: el calor lo acompaña y muestra la intensidad medida allí.\nLa rueda del ratón amplía; el botón derecho arrastra la vista ampliada.\nDoble clic renombra · Supr elimina el seleccionado.",
    "Delt. ant.": "Delt. ant.",
    "Delt. médio": "Delt. medio",
    "Delt. post.": "Delt. post.",
    "ECM": "ECM",
    "ECR": "ECR",
    "Eretor esp.": "Erector esp.",
    "Ext. dedos": "Ext. dedos",
    "FCR": "FCR",
    "Fibular": "Peroneo",
    "Flex. dedos": "Flex. dedos",
    "Frontal": "Frontal",
    "Gastroc. med.": "Gastroc. med.",
    "Glúteo máx.": "Glúteo máx.",
    "Glúteo méd.": "Glúteo med.",
    "Isquiotib.": "Isquiotib.",
    "Lado": "Lado",
    "Lateral": "Lateral",
    "Latíssimo": "Dorsal ancho",
    "Masseter": "Masetero",
    "Orbicular": "Orbicular",
    "Peitoral": "Pectoral",
    "Reto abd.": "Recto abd.",
    "Reto fem.": "Recto fem.",
    "Temporal": "Temporal",
    "Tibial ant.": "Tibial ant.",
    "Trap. sup.": "Trap. sup.",
    "Tríceps": "Tríceps",
    "Vasto lat.": "Vasto lat.",
    "Vasto med.": "Vasto med.",
    "Vista Lateral (perfil esquerdo)": "Vista lateral (perfil izquierdo)",
    "Zigomático": "Cigomático",
}
