# -*- coding: utf-8 -*-
"""Lote "p3_atlas": traduções pt -> fr."""
TRAD = {
    "Bíceps": "Biceps",
    "Clique em 'Adicionar eletrodo' e clique no corpo: o eletrodo cola no\nponto SENIAM mais próximo (ventre do músculo) ou fica onde você clicou.\nARRASTE o eletrodo: o calor acompanha e mostra a intensidade medida ali.\nRoda do mouse amplia; botão direito arrasta a vista ampliada.\nDuplo-clique renomeia · Delete remove o selecionado.": "Cliquez sur « Ajouter une électrode » puis sur le corps : l'électrode se cale sur le\npoint SENIAM le plus proche (ventre du muscle) ou reste où vous avez cliqué.\nFAITES GLISSER l'électrode : la chaleur la suit et montre l'intensité mesurée là.\nLa molette agrandit ; le bouton droit déplace la vue agrandie.\nDouble-clic renomme · Suppr retire l'électrode sélectionnée.",
    "Delt. ant.": "Delt. ant.",
    "Delt. médio": "Delt. moyen",
    "Delt. post.": "Delt. post.",
    "ECM": "SCM",
    "ECR": "ECR",
    "Eretor esp.": "Érecteur rach.",
    "Ext. dedos": "Ext. doigts",
    "FCR": "FCR",
    "Fibular": "Fibulaire",
    "Flex. dedos": "Fléch. doigts",
    "Frontal": "Frontal",
    "Gastroc. med.": "Gastroc. méd.",
    "Glúteo máx.": "Grand fessier",
    "Glúteo méd.": "Moyen fessier",
    "Isquiotib.": "Ischio-jamb.",
    "Lado": "Côté",
    "Lateral": "Latéral",
    "Latíssimo": "Grand dorsal",
    "Masseter": "Masséter",
    "Orbicular": "Orbiculaire",
    "Peitoral": "Pectoral",
    "Reto abd.": "Droit abd.",
    "Reto fem.": "Droit fém.",
    "Temporal": "Temporal",
    "Tibial ant.": "Tibial ant.",
    "Trap. sup.": "Trap. sup.",
    "Tríceps": "Triceps",
    "Vasto lat.": "Vaste lat.",
    "Vasto med.": "Vaste méd.",
    "Vista Lateral (perfil esquerdo)": "Vue latérale (profil gauche)",
    "Zigomático": "Zygomatique",
}
