# -*- coding: utf-8 -*-
"""Lote "p3_atlas": traduções pt -> it."""
TRAD = {
    "Bíceps": "Bicipite",
    "Clique em 'Adicionar eletrodo' e clique no corpo: o eletrodo cola no\nponto SENIAM mais próximo (ventre do músculo) ou fica onde você clicou.\nARRASTE o eletrodo: o calor acompanha e mostra a intensidade medida ali.\nRoda do mouse amplia; botão direito arrasta a vista ampliada.\nDuplo-clique renomeia · Delete remove o selecionado.": "Clicca su 'Aggiungi elettrodo' e poi sul corpo: l'elettrodo si aggancia al\npunto SENIAM più vicino (ventre muscolare) o resta dove hai cliccato.\nTRASCINA l'elettrodo: il calore lo segue e mostra l'intensità misurata lì.\nLa rotella del mouse ingrandisce; il tasto destro trascina la vista ingrandita.\nDoppio clic rinomina · Canc rimuove quello selezionato.",
    "Delt. ant.": "Delt. ant.",
    "Delt. médio": "Delt. medio",
    "Delt. post.": "Delt. post.",
    "ECM": "SCM",
    "ECR": "ECR",
    "Eretor esp.": "Erettore sp.",
    "Ext. dedos": "Est. dita",
    "FCR": "FCR",
    "Fibular": "Peroneo",
    "Flex. dedos": "Fless. dita",
    "Frontal": "Frontale",
    "Gastroc. med.": "Gastroc. med.",
    "Glúteo máx.": "Gluteo max.",
    "Glúteo méd.": "Gluteo med.",
    "Isquiotib.": "Ischiocrur.",
    "Lado": "Lato",
    "Lateral": "Laterale",
    "Latíssimo": "Gran dorsale",
    "Masseter": "Massetere",
    "Orbicular": "Orbicolare",
    "Peitoral": "Pettorale",
    "Reto abd.": "Retto addom.",
    "Reto fem.": "Retto fem.",
    "Temporal": "Temporale",
    "Tibial ant.": "Tibiale ant.",
    "Trap. sup.": "Trap. sup.",
    "Tríceps": "Tricipite",
    "Vasto lat.": "Vasto lat.",
    "Vasto med.": "Vasto med.",
    "Vista Lateral (perfil esquerdo)": "Vista laterale (profilo sinistro)",
    "Zigomático": "Zigomatico",
}
