# -*- coding: utf-8 -*-
"""Lote "p3_atlas": traduções pt -> ja."""
TRAD = {
    "Bíceps": "上腕二頭筋",
    "Clique em 'Adicionar eletrodo' e clique no corpo: o eletrodo cola no\nponto SENIAM mais próximo (ventre do músculo) ou fica onde você clicou.\nARRASTE o eletrodo: o calor acompanha e mostra a intensidade medida ali.\nRoda do mouse amplia; botão direito arrasta a vista ampliada.\nDuplo-clique renomeia · Delete remove o selecionado.": "「電極を追加」をクリックしてから体をクリック：電極は最も近い SENIAM 点（筋腹）に\n吸着するか、クリックした位置に置かれます。\n電極をドラッグ：熱表示が追従し、その位置で測った強さを示します。\nマウスホイールで拡大、右ボタンで拡大表示をドラッグ。\nダブルクリックで名前変更 · Delete で選択した電極を削除。",
    "Delt. ant.": "三角筋前部",
    "Delt. médio": "三角筋中部",
    "Delt. post.": "三角筋後部",
    "ECM": "胸鎖乳突筋",
    "ECR": "橈側手根伸筋",
    "Eretor esp.": "脊柱起立筋",
    "Ext. dedos": "指伸筋",
    "FCR": "橈側手根屈筋",
    "Fibular": "長腓骨筋",
    "Flex. dedos": "指屈筋",
    "Frontal": "前頭筋",
    "Gastroc. med.": "内側腓腹筋",
    "Glúteo máx.": "大殿筋",
    "Glúteo méd.": "中殿筋",
    "Isquiotib.": "ハムストリング",
    "Lado": "側面",
    "Lateral": "外側",
    "Latíssimo": "広背筋",
    "Masseter": "咬筋",
    "Orbicular": "眼輪筋",
    "Peitoral": "大胸筋",
    "Reto abd.": "腹直筋",
    "Reto fem.": "大腿直筋",
    "Temporal": "側頭筋",
    "Tibial ant.": "前脛骨筋",
    "Trap. sup.": "僧帽筋上部",
    "Tríceps": "上腕三頭筋",
    "Vasto lat.": "外側広筋",
    "Vasto med.": "内側広筋",
    "Vista Lateral (perfil esquerdo)": "側面図（左側）",
    "Zigomático": "頬骨筋",
}
