# -*- coding: utf-8 -*-
"""Lote "p3_atlas": traduções pt -> ru."""
TRAD = {
    "Bíceps": "Бицепс",
    "Clique em 'Adicionar eletrodo' e clique no corpo: o eletrodo cola no\nponto SENIAM mais próximo (ventre do músculo) ou fica onde você clicou.\nARRASTE o eletrodo: o calor acompanha e mostra a intensidade medida ali.\nRoda do mouse amplia; botão direito arrasta a vista ampliada.\nDuplo-clique renomeia · Delete remove o selecionado.": "Нажмите «Добавить электрод», затем щёлкните по телу: электрод прилипнет к\nближайшей точке SENIAM (брюшко мышцы) или останется там, где вы щёлкнули.\nПЕРЕТАЩИТЕ электрод: тепло следует за ним и показывает измеренную там интенсивность.\nКолесо мыши увеличивает; правая кнопка перетаскивает увеличенный вид.\nДвойной щелчок переименовывает · Delete удаляет выбранный.",
    "Delt. ant.": "Пер. дельта",
    "Delt. médio": "Ср. дельта",
    "Delt. post.": "Задн. дельта",
    "ECM": "ГКС",
    "ECR": "ЛРК",
    "Eretor esp.": "Разгиб. спины",
    "Ext. dedos": "Разгиб. пальцев",
    "FCR": "ЛСК",
    "Fibular": "Малоберц.",
    "Flex. dedos": "Сгиб. пальцев",
    "Frontal": "Лобная",
    "Gastroc. med.": "Мед. икронож.",
    "Glúteo máx.": "Больш. ягод.",
    "Glúteo méd.": "Сред. ягод.",
    "Isquiotib.": "Задн. бедра",
    "Lado": "Сбоку",
    "Lateral": "Латеральная",
    "Latíssimo": "Широчайшая",
    "Masseter": "Жевательная",
    "Orbicular": "Круговая глаза",
    "Peitoral": "Грудная",
    "Reto abd.": "Прямая живота",
    "Reto fem.": "Прямая бедра",
    "Temporal": "Височная",
    "Tibial ant.": "Передн. большеберц.",
    "Trap. sup.": "Верх. трапец.",
    "Tríceps": "Трицепс",
    "Vasto lat.": "Лат. широкая",
    "Vasto med.": "Мед. широкая",
    "Vista Lateral (perfil esquerdo)": "Вид сбоку (левый профиль)",
    "Zigomático": "Скуловая",
}
