# -*- coding: utf-8 -*-
"""Lote "p3_atlas": traduções pt -> zh."""
TRAD = {
    "Bíceps": "肱二头肌",
    "Clique em 'Adicionar eletrodo' e clique no corpo: o eletrodo cola no\nponto SENIAM mais próximo (ventre do músculo) ou fica onde você clicou.\nARRASTE o eletrodo: o calor acompanha e mostra a intensidade medida ali.\nRoda do mouse amplia; botão direito arrasta a vista ampliada.\nDuplo-clique renomeia · Delete remove o selecionado.": "点击“添加电极”，再点击身体：电极会贴到最近的 SENIAM 点（肌腹），\n或停在您点击的位置。\n拖动电极：热区会跟随并显示该处测得的强度。\n鼠标滚轮缩放；右键拖动放大后的视图。\n双击重命名 · Delete 删除所选电极。",
    "Delt. ant.": "三角肌前束",
    "Delt. médio": "三角肌中束",
    "Delt. post.": "三角肌后束",
    "ECM": "胸锁乳突肌",
    "ECR": "桡侧腕伸肌",
    "Eretor esp.": "竖脊肌",
    "Ext. dedos": "指伸肌",
    "FCR": "桡侧腕屈肌",
    "Fibular": "腓骨长肌",
    "Flex. dedos": "指屈肌",
    "Frontal": "额肌",
    "Gastroc. med.": "腓肠肌内侧",
    "Glúteo máx.": "臀大肌",
    "Glúteo méd.": "臀中肌",
    "Isquiotib.": "腘绳肌",
    "Lado": "侧面",
    "Lateral": "外侧",
    "Latíssimo": "背阔肌",
    "Masseter": "咬肌",
    "Orbicular": "眼轮匝肌",
    "Peitoral": "胸大肌",
    "Reto abd.": "腹直肌",
    "Reto fem.": "股直肌",
    "Temporal": "颞肌",
    "Tibial ant.": "胫骨前肌",
    "Trap. sup.": "上斜方肌",
    "Tríceps": "肱三头肌",
    "Vasto lat.": "股外侧肌",
    "Vasto med.": "股内侧肌",
    "Vista Lateral (perfil esquerdo)": "侧视图（左侧面）",
    "Zigomático": "颧肌",
}
